# Application configuration
[app]
# Debug level
level = "info"

# Only sqlite3 is supported as database.
[sqlite]
path = "db/db.sqlite3"

# Uncomment to start the telegram bot
# [telegram]
# token = ""
# server = ""

