use super::TextKey;

/// Returns the English translation for a text key.
#[must_use]
pub fn get(key: TextKey) -> &'static str {
    match key {
        // Sections
        TextKey::SectionHome => "Home",
        TextKey::SectionTransactions => "Transactions",
        TextKey::SectionWallets => "Wallets",
        TextKey::SectionFlows => "Flows",
        TextKey::SectionCategories => "Categories",
        TextKey::SectionMembers => "Members",
        TextKey::SectionVault => "Vault",
        TextKey::SectionStats => "Statistics",
        TextKey::SectionPreferences => "Preferences",

        // Form Labels
        TextKey::LabelAmount => "Amount",
        TextKey::LabelWallet => "Wallet",
        TextKey::LabelFlow => "Flow",
        TextKey::LabelCategory => "Category",
        TextKey::LabelNote => "Note",
        TextKey::LabelOccurredAt => "Date",
        TextKey::LabelFrom => "From",
        TextKey::LabelTo => "To",
        TextKey::LabelName => "Name",
        TextKey::LabelUsername => "Username",
        TextKey::LabelRole => "Role",
        TextKey::LabelOpeningBalance => "Opening balance",
        TextKey::LabelCap => "Cap",

        // Form Titles
        TextKey::TitleNewExpense => "New Expense",
        TextKey::TitleNewIncome => "New Income",
        TextKey::TitleNewRefund => "New Refund",
        TextKey::TitleNewTransfer => "New Transfer",
        TextKey::TitleEditTransaction => "Edit Transaction",
        TextKey::TitleNewWallet => "New Wallet",
        TextKey::TitleEditWallet => "Edit Wallet",
        TextKey::TitleNewFlow => "New Flow",
        TextKey::TitleEditFlow => "Edit Flow",
        TextKey::TitleNewCategory => "New Category",
        TextKey::TitleEditCategory => "Edit Category",
        TextKey::TitleNewMember => "New Member",
        TextKey::TitleEditMember => "Edit Member",
        TextKey::TitleNewVault => "New Vault",
        TextKey::TitleVaultDefaults => "Vault Settings",
        TextKey::TitleSelectVault => "Select Vault",

        // Validation Errors
        TextKey::ValidationRequired => "Required field",
        TextKey::ValidationAmountRequired => "Amount required",
        TextKey::ValidationAmountInvalid => "Invalid amount",
        TextKey::ValidationAmountPositive => "Amount must be positive",
        TextKey::ValidationAmountNegative => "Amount must be negative",
        TextKey::ValidationDateRequired => "Date required",
        TextKey::ValidationDateInvalid => "Invalid date format (YYYY-MM-DD HH:MM)",
        TextKey::ValidationDateInvalidTimezone => "Invalid timezone",
        TextKey::ValidationLengthMin => "Minimum {min} characters",
        TextKey::ValidationLengthMax => "Maximum {max} characters",
        TextKey::ValidationWalletRequired => "Select a wallet",
        TextKey::ValidationFlowRequired => "Select a flow",
        TextKey::ValidationCategoryRequired => "Select a category",
        TextKey::ValidationNameRequired => "Name required",
        TextKey::ValidationUsernameRequired => "Username required",
        TextKey::ValidationRoleRequired => "Role required",
        TextKey::ValidationFromRequired => "Source required",
        TextKey::ValidationToRequired => "Destination required",
        TextKey::ValidationTransferSameSource => "Choose two different wallets.",
        TextKey::ValidationTransferSameDestination => "Choose two different flows.",
        TextKey::ValidationTransferSameElements => "Choose two different elements.",
        TextKey::ValidationTransferMinimumTwo => "At least 2 elements required.",
        TextKey::ValidationWalletInvalid => "Invalid wallet.",
        TextKey::ValidationFlowInvalid => "Invalid flow.",
        TextKey::ValidationCategoryInvalid => "Invalid category.",
        TextKey::ValidationOpeningBalanceInvalid => "Invalid opening balance.",
        TextKey::ValidationCapInvalid => "Invalid cap.",
        TextKey::ValidationCapMustBePositive => "Cap must be > 0.",
        TextKey::ValidationOpeningBalanceNonNegative => "Opening allocation must be >= 0.",
        TextKey::ValidationNoWalletSelected => "No wallet selected.",
        TextKey::ValidationNoFlowSelected => "No flow selected.",
        TextKey::ValidationNoTransactionToVoid => "No transaction to void.",
        TextKey::ValidationUnallocatedCannotRename => "Unallocated cannot be renamed.",
        TextKey::ValidationUnallocatedCannotArchive => "Unallocated cannot be archived.",
        TextKey::ValidationAlreadyArchived => "Already archived.",
        TextKey::ValidationSystemCategoryImmutable => "System categories cannot be modified.",

        // Empty States
        TextKey::EmptyTransactions => "No transactions",
        TextKey::EmptyWallets => "No wallets",
        TextKey::EmptyFlows => "No flows",
        TextKey::EmptyCategories => "No categories",
        TextKey::EmptyMembers => "No members",
        TextKey::EmptyVaults => "No vaults",
        TextKey::EmptyStats => "No statistics available",
        TextKey::EmptyResults => "No results",

        // Actions
        TextKey::ActionSave => "Save",
        TextKey::ActionCancel => "Cancel",
        TextKey::ActionCreate => "Create",
        TextKey::ActionEdit => "Edit",
        TextKey::ActionDelete => "Delete",
        TextKey::ActionArchive => "Archive",
        TextKey::ActionVoid => "Void",
        TextKey::ActionRefund => "Refund",
        TextKey::ActionTransfer => "Transfer",
        TextKey::ActionConfirm => "Confirm",
        TextKey::ActionBack => "Back",
        TextKey::ActionRefresh => "Refresh",

        // Hints - General
        TextKey::HintPressEnter => "Press Enter to confirm",
        TextKey::HintPressEsc => "Press Esc to cancel",
        TextKey::HintPressTab => "Press Tab to go to next field",
        TextKey::HintSelectWithArrows => "Use arrows to select",
        TextKey::HintTypeToSearch => "Type to search",
        TextKey::HintLoadingData => "Loading...",
        TextKey::HintNoSelection => "No selection",
        TextKey::HintConfirmDelete => "Press again to confirm",

        // Hints - Footer Navigation
        TextKey::HintHome => "home",
        TextKey::HintTransactions => "txn",
        TextKey::HintAccounts => "accounts",
        TextKey::HintAnalytics => "analytics",
        TextKey::HintSettings => "settings",

        // Hints - Footer Actions
        TextKey::HintQuickAdd => "quick add",
        TextKey::HintHelp => "help",
        TextKey::HintCreate => "create",
        TextKey::HintEdit => "edit",
        TextKey::HintDelete => "delete",
        TextKey::HintSave => "save",
        TextKey::HintCancel => "cancel",
        TextKey::HintBack => "back",
        TextKey::HintRefresh => "refresh",
        TextKey::HintAdd => "add",
        TextKey::HintToggle => "toggle",
        TextKey::HintCategorize => "categorize",
        TextKey::HintExit => "exit",

        // Help Overlay
        TextKey::HelpTitle => "Keyboard Shortcuts",
        TextKey::HelpCloseHelp => "close help",
        TextKey::HelpGlobal => "Global",
        TextKey::HelpNavigation => "Navigation",
        TextKey::HelpCommonActions => "Common Actions",
        TextKey::HelpQuickAddTxn => "Quick add transaction",
        TextKey::HelpNewTxnModal => "New transaction (modal)",
        TextKey::HelpCommandPalette => "Command palette",
        TextKey::HelpSearch => "Search",
        TextKey::HelpShowHelp => "Show/hide help",
        TextKey::HelpNextSubTab => "Next sub-tab",
        TextKey::HelpPrevSubTab => "Prev sub-tab",
        TextKey::HelpNavigateList => "Navigate list",
        TextKey::HelpOpenDetails => "Open details",
        TextKey::HelpBackClose => "Back / Close",
        TextKey::HelpEditSelected => "Edit selected",
        TextKey::HelpDeleteSelected => "Delete selected",
        TextKey::HelpNavigateFeed => "Navigate feed",
        TextKey::HelpGoToTransactions => "Go to Transactions",
        TextKey::HelpGoToAccounts => "Go to Accounts",
        TextKey::HelpGoToAnalytics => "Go to Analytics",
        TextKey::HelpGoToSettings => "Go to Settings",
        TextKey::HelpNewIncome => "New income",
        TextKey::HelpNewRefund => "New refund",
        TextKey::HelpNewTransfer => "New transfer",
        TextKey::HelpToggleFilters => "Toggle filters",
        TextKey::HelpGroupTxns => "Group transactions",
        TextKey::HelpScopeWallet => "Scope to wallet",
        TextKey::HelpScopeFlow => "Scope to flow",
        TextKey::HelpClearFilters => "Clear filters",
        TextKey::HelpDeleteTxn => "Delete transaction",
        TextKey::HelpUndoDelete => "Undo delete (when shown)",
        TextKey::HelpToggleVoided => "Toggle voided",
        TextKey::HelpNextPrevPage => "Next/prev page",
        TextKey::HelpVisualMode => "Visual Mode",
        TextKey::HelpToggleVisual => "Toggle visual mode",
        TextKey::HelpSelectTxn => "Select transaction",
        TextKey::HelpExitVisual => "Exit visual mode",
        TextKey::HelpDetailView => "Detail View",
        TextKey::HelpEditTxn => "Edit transaction",
        TextKey::HelpRepeatTxn => "Repeat transaction",
        TextKey::HelpVoidTxn => "Void transaction",
        TextKey::HelpForm => "Form",
        TextKey::HelpNextField => "Next field",
        TextKey::HelpChangeValue => "Change value",
        TextKey::HelpFilters => "Filters",
        TextKey::HelpToggleType => "Toggle type",
        TextKey::HelpToggleScope => "Toggle scope",
        TextKey::HelpApply => "Apply",
        TextKey::HelpJumpSubTab => "Jump to sub-tab",
        TextKey::HelpSourcesWallets => "Sources (Wallets)",
        TextKey::HelpCreateWallet => "Create wallet",
        TextKey::HelpRenameWallet => "Rename wallet",
        TextKey::HelpDeleteArchive => "Delete (archive)",
        TextKey::HelpViewDetails => "View details",
        TextKey::HelpEnvelopesFlows => "Envelopes (Flows)",
        TextKey::HelpCreateEnvelope => "Create envelope",
        TextKey::HelpRenameEnvelope => "Rename envelope",
        TextKey::HelpChangeMode => "Change mode",
        TextKey::HelpGoals => "Goals",
        TextKey::HelpComingSoon => "(coming soon)",
        TextKey::HelpRefreshData => "Refresh data",
        TextKey::HelpSwitchView => "Switch view",
        TextKey::HelpCashSpendWorth => "Cash/Spend/Worth",
        TextKey::HelpChangePeriod => "Change period",
        TextKey::HelpCreateCategory => "Create category",
        TextKey::HelpRenameCategory => "Rename category",
        TextKey::HelpManageAliases => "Manage aliases",
        TextKey::HelpMergeCategories => "Merge categories",
        TextKey::HelpAliases => "Aliases",
        TextKey::HelpSwitchFocus => "Switch focus",
        TextKey::HelpDeleteAlias => "Delete alias",
        TextKey::HelpAddSave => "Add/Save",
        TextKey::HelpVault => "Vault",
        TextKey::HelpCreateVault => "Create vault",
        TextKey::HelpSelectVault => "Select vault",
        TextKey::HelpMembers => "Members",
        TextKey::HelpAddMember => "Add member",
        TextKey::HelpEditMember => "Edit member",
        TextKey::HelpRemoveMember => "Remove member",
        TextKey::HelpVaultMembers => "Vault members",
        TextKey::HelpFlowSharing => "Flow sharing",
        TextKey::HelpChangeFlow => "Change flow",
        TextKey::HelpChangeRole => "Change role",

        // Success Messages
        TextKey::SuccessCreated => "Created successfully",
        TextKey::SuccessUpdated => "Updated successfully",
        TextKey::SuccessDeleted => "Deleted successfully",
        TextKey::SuccessArchived => "Archived successfully",
        TextKey::SuccessVoided => "Voided successfully",
        TextKey::SuccessRefreshed => "Data refreshed",
        TextKey::SuccessTransactionSaved => "Transaction saved.",
        TextKey::SuccessTransactionUpdated => "Transaction updated.",
        TextKey::SuccessTransactionVoided => "Transaction voided.",
        TextKey::SuccessTransactionRepeated => "Transaction repeated.",
        TextKey::SuccessTransferWalletSaved => "Wallet transfer saved.",
        TextKey::SuccessTransferWalletUpdated => "Wallet transfer updated.",
        TextKey::SuccessTransferFlowSaved => "Flow transfer saved.",
        TextKey::SuccessTransferFlowUpdated => "Flow transfer updated.",
        TextKey::SuccessWalletCreated => "Wallet created.",
        TextKey::SuccessWalletUpdated => "Wallet updated.",
        TextKey::SuccessWalletRestored => "Wallet restored.",
        TextKey::SuccessFlowCreated => "Flow created.",
        TextKey::SuccessFlowUpdated => "Flow updated.",
        TextKey::SuccessFlowRestored => "Flow restored.",
        TextKey::SuccessCategoryCreated => "Category created.",
        TextKey::SuccessCategoryUpdated => "Category updated.",
        TextKey::SuccessAliasCreated => "Alias created.",
        TextKey::SuccessAliasDeleted => "Alias deleted.",
        TextKey::SuccessVaultCreated => "Vault created.",
        TextKey::SuccessVaultSelected => "Vault selected.",
        TextKey::SuccessDefaultsSaved => "Defaults saved.",
        TextKey::SuccessMergeCompleted => "Merge completed.",
        TextKey::SuccessMergePreviewOk => "Preview ok. Press Enter to confirm.",

        // Error Messages
        TextKey::ErrorGeneric => "An error occurred",
        TextKey::ErrorNetwork => "Connection error",
        TextKey::ErrorNotFound => "Not found",
        TextKey::ErrorUnauthorized => "Unauthorized",
        TextKey::ErrorSaving => "Error saving.",
        TextKey::ErrorUpdating => "Error updating.",
        TextKey::ErrorDeleting => "Error deleting.",
        TextKey::ErrorArchiving => "Error archiving.",
        TextKey::ErrorRestoring => "Error restoring.",
        TextKey::ErrorVoiding => "Error voiding transaction.",
        TextKey::ErrorRepeating => "Error repeating transaction.",
        TextKey::ErrorConnection => "Connection error",
        TextKey::ErrorTransferWallet => "Wallet transfer error.",
        TextKey::ErrorTransferFlow => "Flow transfer error.",
        TextKey::ErrorCreateWallet => "Failed to create wallet.",
        TextKey::ErrorUpdateWallet => "Failed to update wallet.",
        TextKey::ErrorArchiveWallet => "Error archiving wallet.",
        TextKey::ErrorRestoreWallet => "Error restoring wallet.",
        TextKey::ErrorCreateFlow => "Failed to create flow.",
        TextKey::ErrorUpdateFlow => "Failed to update flow.",
        TextKey::ErrorArchiveFlow => "Failed to archive flow.",
        TextKey::ErrorRestoreFlow => "Error restoring flow.",
        TextKey::ErrorCreateCategory => "Error creating category.",
        TextKey::ErrorUpdateCategory => "Error updating category.",
        TextKey::ErrorArchiveCategory => "Error archiving category.",
        TextKey::ErrorCreateAlias => "Error creating alias.",
        TextKey::ErrorDeleteAlias => "Error deleting alias.",
        TextKey::ErrorCreateVault => "Error creating vault.",
        TextKey::ErrorDeleteVault => "Error deleting vault.",
        TextKey::ErrorSaveDefaults => "Error saving defaults.",
        TextKey::ErrorMergeCategories => "Invalid merge. Check conflicts.",

        // Misc
        TextKey::MiscYes => "Yes",
        TextKey::MiscNo => "No",
        TextKey::MiscAll => "All",
        TextKey::MiscNone => "None",

        // Status bar
        TextKey::StatusOnline => "online",
        TextKey::StatusOffline => "offline",

        // Section Labels (Capitalized for tab bar)
        TextKey::SectionAccounts => "Accounts",
        TextKey::SectionAnalytics => "Analytics",
        TextKey::SectionSettings => "Settings",

        // Transfer picker
        TextKey::TransferPickerTitle => "Transfer Type",
        TextKey::TransferPickerWallet => "Wallet Transfer",
        TextKey::TransferPickerFlow => "Flow Transfer",

        // UI Improvements - Stats
        TextKey::StatsQuickActionRefresh => "refresh",
        TextKey::StatsQuickActionPeriod => "period",
        TextKey::StatsTrendExcellent => "EXCELLENT",
        TextKey::StatsTrendGood => "GOOD",
        TextKey::StatsTrendStable => "STABLE",
        TextKey::StatsTrendDeclining => "DECLINING",
        TextKey::StatsTrendCaution => "CAUTION",
        TextKey::StatsTrendRising => "RISING",

        // UI Improvements - Accounts
        TextKey::AccountsWelcomeTitle => "Welcome!",
        TextKey::AccountsWelcomeDesc => "Let's create your first wallet to start tracking your finances.",
        TextKey::AccountsEnvelopesTitle => "Budget with Envelopes",
        TextKey::AccountsEnvelopesDesc => "Create envelopes to organize and track spending by category or goal.",
        TextKey::AccountsQuickCreate => "Quick create",
        TextKey::AccountsCreateDetails => "Create with details",

        // UI Improvements - Transactions
        TextKey::TransactionsFilterTypes => "Transaction Types",
        TextKey::TransactionsSyntaxHelp => "Syntax: [+]amount note [#category] [@wallet] [>envelope]",

        // Error Messages - API/Login
        TextKey::ErrorInvalidCredentials => "Invalid credentials or missing pairing.",
        TextKey::ErrorMembershipLastOwner => "Cannot remove the last owner of the flow.",
        TextKey::ErrorMembershipOwnerImmutable => "Cannot change the vault owner's role.",
        TextKey::ErrorMembershipOwnerRemoveForbidden => "Cannot remove the vault owner.",
        TextKey::ErrorOperationForbidden => "Operation not permitted.",
        TextKey::ErrorResourceNotFound => "Resource not found.",
        TextKey::ErrorConflict => "Conflict: {message}",
        TextKey::ErrorValidation => "Validation error: {message}",
        TextKey::ErrorValidationAmbiguousVault => "Vault name is ambiguous. Use \"Main (owner)\" or a vault id.",
        TextKey::ErrorBadRequest => "Bad request: {message}",
        TextKey::ErrorServerError => "Server error: {message}",
        TextKey::ErrorServerUnreachable => "Server unreachable: {error}",

        // State Messages
        TextKey::StateSnapshotUnavailable => "Snapshot unavailable.",
        TextKey::StateVaultUnavailable => "Vault unavailable.",
        TextKey::StateUserUnavailable => "User unavailable.",
        TextKey::StateNoWalletAvailable => "No wallet available.",
        TextKey::StateUnallocatedMissing => "Unallocated flow missing.",
        TextKey::StateCannotDetermineWalletTransfer => "Cannot determine transfer wallets.",
        TextKey::StateCannotDetermineFlowTransfer => "Cannot determine transfer flows.",

        // UI Labels
        TextKey::UiVaultLabel => "Vault",
        TextKey::UiUserLabel => "User",
        TextKey::UiMainLabel => "Main",
        TextKey::UiFetchingVaultData => "Fetching vault data",
        TextKey::UiNoData => "No data",
        TextKey::UiOther => "Other",
        TextKey::UiError => "Error",
        TextKey::UiConnectionError => "Connection Error",
        TextKey::UiUnableToConnect => "Unable to connect to server.",
        TextKey::UiFailedToDeleteVault => "Failed to delete vault.",
        TextKey::UiTypeToSearchAllData => "Type to search across all data",
        TextKey::UiNoMatchingResults => "No matching results",

        // Dialog/Modal Labels
        TextKey::DialogBulkCategorizeTitle => "Bulk Categorize",
        TextKey::DialogBulkCategorizeConfirm => "Apply",
        TextKey::DialogBulkCategorizeCancel => "Cancel",
        TextKey::DialogGroupByDate => "Date",
        TextKey::DialogGroupByCategory => "Category",
        TextKey::DialogGroupByWallet => "Wallet",
        TextKey::DialogGroupByEnvelope => "Envelope",
        TextKey::DialogCancel => "Cancel",

        // Prompts and Hints
        TextKey::PromptEnterName => "Enter a name.",
        TextKey::PromptEnterUsername => "Enter a username.",
        TextKey::PromptEnterAlias => "Enter an alias.",
        TextKey::PromptEnterCap => "Enter a cap.",
        TextKey::PromptFillAllFields => "Fill all fields.",
        TextKey::PromptUseDedicatedTransferForm => "Use the dedicated transfer form.",
        TextKey::PromptAtLeastTwoCategories => "At least 2 categories required to merge.",
        TextKey::PromptSourceCategoryInvalid => "Source category invalid.",
        TextKey::PromptDestinationCategoryInvalid => "Destination category invalid.",
        TextKey::PromptPressEnterToConfirm => "Preview ok. Press Enter to confirm.",
        TextKey::PromptCheckConflicts => "Invalid merge. Check conflicts.",
        TextKey::PromptNoShareableFlows => "No shareable flows.",
        TextKey::PromptNoMemberSelected => "No member selected.",
        TextKey::PromptNoAliasSelected => "No alias selected.",
        TextKey::PromptNoCategorySelected => "No category selected.",
        TextKey::PromptEnterCategory => "Enter a category.",

        // Quick Add / Parsing Errors
        TextKey::QuickAddEnterAmount => "Enter an amount.",
        TextKey::QuickAddAmountMissing => "Amount missing.",
        TextKey::QuickAddAmountInvalid => "Invalid amount.",
        TextKey::QuickAddAmountMustBePositive => "Amount must be > 0.",
        TextKey::QuickAddTooManyCategories => "Too many tags: maximum 1.",
        TextKey::QuickAddTooManyWallets => "Too many wallets: maximum 1.",
        TextKey::QuickAddTooManyEnvelopes => "Too many envelopes: maximum 1.",
        TextKey::QuickAddSpecifyTwoWallets => "Specify exactly 2 wallets (@from @to).",
        TextKey::QuickAddSpecifyTwoFlows => "Specify exactly 2 flows (>from >to).",
        TextKey::QuickAddWalletNotFound => "Wallet not found: @{query}",
        TextKey::QuickAddEnvelopeNotFound => "Envelope not found: >{query}",
        TextKey::QuickAddFlowNotFound => "Flow not found: >{query}",
        TextKey::QuickAddWalletsMustBeDifferent => "The two wallets must be different.",
        TextKey::QuickAddFlowsMustBeDifferent => "The two flows must be different.",

        // Validation Errors - Additional
        TextKey::ValidationNoTransactionSelected => "No transaction selected.",
        TextKey::ValidationNoWalletAvailable => "No wallet available.",
        TextKey::ValidationNoFlowAvailable => "No flow available.",
        TextKey::ValidationNoElementAvailable => "No element available.",
        TextKey::ValidationTransactionVoided => "Voided transaction: editing not available.",
        TextKey::ValidationTransactionInvalid => "Invalid transaction.",
        TextKey::ValidationTransferWalletInvalid => "Invalid wallet transfer.",
        TextKey::ValidationTransferFlowInvalid => "Invalid flow transfer.",
        TextKey::ValidationWalletArchived => "Archived wallet: editing not available.",
        TextKey::ValidationFlowArchived => "Archived flow: editing not available.",
        TextKey::ValidationSnapshotUnavailable => "Snapshot unavailable.",

        // Success Messages - Additional
        TextKey::SuccessDeletedItem => "Deleted \"{label}\" ({amount})",
        TextKey::SuccessDeletedMultiple => "Deleted {count} transactions",
        TextKey::SuccessCategorizedTransactions => "Categorized {count} transactions as #{category}",
        TextKey::SuccessDeletedWallet => "Deleted \"{name}\"",
        TextKey::SuccessDeletedFlow => "Deleted \"{name}\"",

        // UI Labels - Additional
        TextKey::UiNoDetailAvailable => "No detail available.",
        TextKey::UiNoElement => "No element.",
        TextKey::UiNoRecentCategories => "No recent categories.",
        TextKey::UiRecentCategories => "Recent categories",
        TextKey::UiTransactionDetail => "Transaction Detail",
    }
}
