use super::TextKey;

/// Returns the English translation for a text key.
#[must_use]
pub fn get(key: TextKey) -> &'static str {
    match key {
        // Sections
        TextKey::SectionHome => "Home",
        TextKey::SectionTransactions => "Transactions",
        TextKey::SectionWallets => "Wallets",
        TextKey::SectionFlows => "Flows",
        TextKey::SectionCategories => "Categories",
        TextKey::SectionMembers => "Members",
        TextKey::SectionVault => "Vault",
        TextKey::SectionStats => "Statistics",

        // Form Labels
        TextKey::LabelAmount => "Amount",
        TextKey::LabelWallet => "Wallet",
        TextKey::LabelFlow => "Flow",
        TextKey::LabelCategory => "Category",
        TextKey::LabelNote => "Note",
        TextKey::LabelOccurredAt => "Date",
        TextKey::LabelFrom => "From",
        TextKey::LabelTo => "To",
        TextKey::LabelName => "Name",
        TextKey::LabelUsername => "Username",
        TextKey::LabelRole => "Role",
        TextKey::LabelOpeningBalance => "Opening balance",
        TextKey::LabelCap => "Cap",

        // Form Titles
        TextKey::TitleNewExpense => "New Expense",
        TextKey::TitleNewIncome => "New Income",
        TextKey::TitleNewRefund => "New Refund",
        TextKey::TitleNewTransfer => "New Transfer",
        TextKey::TitleEditTransaction => "Edit Transaction",
        TextKey::TitleNewWallet => "New Wallet",
        TextKey::TitleEditWallet => "Edit Wallet",
        TextKey::TitleNewFlow => "New Flow",
        TextKey::TitleEditFlow => "Edit Flow",
        TextKey::TitleNewCategory => "New Category",
        TextKey::TitleEditCategory => "Edit Category",
        TextKey::TitleNewMember => "New Member",
        TextKey::TitleEditMember => "Edit Member",
        TextKey::TitleNewVault => "New Vault",
        TextKey::TitleVaultDefaults => "Vault Settings",
        TextKey::TitleSelectVault => "Select Vault",

        // Validation Errors
        TextKey::ValidationRequired => "Required field",
        TextKey::ValidationAmountRequired => "Amount required",
        TextKey::ValidationAmountInvalid => "Invalid amount",
        TextKey::ValidationAmountPositive => "Amount must be positive",
        TextKey::ValidationAmountNegative => "Amount must be negative",
        TextKey::ValidationDateRequired => "Date required",
        TextKey::ValidationDateInvalid => "Invalid date format (YYYY-MM-DD HH:MM)",
        TextKey::ValidationDateInvalidTimezone => "Invalid timezone",
        TextKey::ValidationLengthMin => "Minimum {min} characters",
        TextKey::ValidationLengthMax => "Maximum {max} characters",
        TextKey::ValidationWalletRequired => "Select a wallet",
        TextKey::ValidationFlowRequired => "Select a flow",
        TextKey::ValidationCategoryRequired => "Select a category",
        TextKey::ValidationNameRequired => "Name required",
        TextKey::ValidationUsernameRequired => "Username required",
        TextKey::ValidationRoleRequired => "Role required",
        TextKey::ValidationFromRequired => "Source required",
        TextKey::ValidationToRequired => "Destination required",

        // Empty States
        TextKey::EmptyTransactions => "No transactions",
        TextKey::EmptyWallets => "No wallets",
        TextKey::EmptyFlows => "No flows",
        TextKey::EmptyCategories => "No categories",
        TextKey::EmptyMembers => "No members",
        TextKey::EmptyVaults => "No vaults",
        TextKey::EmptyStats => "No statistics available",
        TextKey::EmptyResults => "No results",

        // Actions
        TextKey::ActionSave => "Save",
        TextKey::ActionCancel => "Cancel",
        TextKey::ActionCreate => "Create",
        TextKey::ActionEdit => "Edit",
        TextKey::ActionDelete => "Delete",
        TextKey::ActionArchive => "Archive",
        TextKey::ActionVoid => "Void",
        TextKey::ActionRefund => "Refund",
        TextKey::ActionTransfer => "Transfer",
        TextKey::ActionConfirm => "Confirm",
        TextKey::ActionBack => "Back",
        TextKey::ActionRefresh => "Refresh",

        // Hints - General
        TextKey::HintPressEnter => "Press Enter to confirm",
        TextKey::HintPressEsc => "Press Esc to cancel",
        TextKey::HintPressTab => "Press Tab to go to next field",
        TextKey::HintSelectWithArrows => "Use arrows to select",
        TextKey::HintTypeToSearch => "Type to search",
        TextKey::HintLoadingData => "Loading...",
        TextKey::HintNoSelection => "No selection",
        TextKey::HintConfirmDelete => "Press again to confirm",

        // Hints - Footer Navigation
        TextKey::HintHome => "home",
        TextKey::HintTransactions => "txn",
        TextKey::HintAccounts => "accounts",
        TextKey::HintAnalytics => "analytics",
        TextKey::HintSettings => "settings",

        // Hints - Footer Actions
        TextKey::HintQuickAdd => "quick add",
        TextKey::HintHelp => "help",
        TextKey::HintCreate => "create",
        TextKey::HintEdit => "edit",
        TextKey::HintDelete => "delete",
        TextKey::HintSave => "save",
        TextKey::HintCancel => "cancel",
        TextKey::HintBack => "back",
        TextKey::HintRefresh => "refresh",
        TextKey::HintAdd => "add",
        TextKey::HintToggle => "toggle",
        TextKey::HintCategorize => "categorize",
        TextKey::HintExit => "exit",

        // Help Overlay
        TextKey::HelpTitle => "Keyboard Shortcuts",
        TextKey::HelpCloseHelp => "close help",
        TextKey::HelpGlobal => "Global",
        TextKey::HelpNavigation => "Navigation",
        TextKey::HelpCommonActions => "Common Actions",
        TextKey::HelpQuickAddTxn => "Quick add transaction",
        TextKey::HelpNewTxnModal => "New transaction (modal)",
        TextKey::HelpCommandPalette => "Command palette",
        TextKey::HelpSearch => "Search",
        TextKey::HelpShowHelp => "Show/hide help",
        TextKey::HelpNextSubTab => "Next sub-tab",
        TextKey::HelpPrevSubTab => "Prev sub-tab",
        TextKey::HelpNavigateList => "Navigate list",
        TextKey::HelpOpenDetails => "Open details",
        TextKey::HelpBackClose => "Back / Close",
        TextKey::HelpEditSelected => "Edit selected",
        TextKey::HelpDeleteSelected => "Delete selected",
        TextKey::HelpNavigateFeed => "Navigate feed",
        TextKey::HelpGoToTransactions => "Go to Transactions",
        TextKey::HelpGoToAccounts => "Go to Accounts",
        TextKey::HelpGoToAnalytics => "Go to Analytics",
        TextKey::HelpGoToSettings => "Go to Settings",
        TextKey::HelpNewIncome => "New income",
        TextKey::HelpNewRefund => "New refund",
        TextKey::HelpToggleFilters => "Toggle filters",
        TextKey::HelpGroupTxns => "Group transactions",
        TextKey::HelpScopeWallet => "Scope to wallet",
        TextKey::HelpScopeFlow => "Scope to flow",
        TextKey::HelpClearFilters => "Clear filters",
        TextKey::HelpDeleteTxn => "Delete transaction",
        TextKey::HelpUndoDelete => "Undo delete (when shown)",
        TextKey::HelpToggleVoided => "Toggle voided",
        TextKey::HelpNextPrevPage => "Next/prev page",
        TextKey::HelpVisualMode => "Visual Mode",
        TextKey::HelpToggleVisual => "Toggle visual mode",
        TextKey::HelpSelectTxn => "Select transaction",
        TextKey::HelpExitVisual => "Exit visual mode",
        TextKey::HelpDetailView => "Detail View",
        TextKey::HelpEditTxn => "Edit transaction",
        TextKey::HelpRepeatTxn => "Repeat transaction",
        TextKey::HelpVoidTxn => "Void transaction",
        TextKey::HelpForm => "Form",
        TextKey::HelpNextField => "Next field",
        TextKey::HelpChangeValue => "Change value",
        TextKey::HelpFilters => "Filters",
        TextKey::HelpToggleType => "Toggle type",
        TextKey::HelpToggleScope => "Toggle scope",
        TextKey::HelpApply => "Apply",
        TextKey::HelpJumpSubTab => "Jump to sub-tab",
        TextKey::HelpSourcesWallets => "Sources (Wallets)",
        TextKey::HelpCreateWallet => "Create wallet",
        TextKey::HelpRenameWallet => "Rename wallet",
        TextKey::HelpDeleteArchive => "Delete (archive)",
        TextKey::HelpViewDetails => "View details",
        TextKey::HelpEnvelopesFlows => "Envelopes (Flows)",
        TextKey::HelpCreateEnvelope => "Create envelope",
        TextKey::HelpRenameEnvelope => "Rename envelope",
        TextKey::HelpChangeMode => "Change mode",
        TextKey::HelpGoals => "Goals",
        TextKey::HelpComingSoon => "(coming soon)",
        TextKey::HelpRefreshData => "Refresh data",
        TextKey::HelpSwitchView => "Switch view",
        TextKey::HelpCashSpendWorth => "Cash/Spend/Worth",
        TextKey::HelpChangePeriod => "Change period",
        TextKey::HelpCreateCategory => "Create category",
        TextKey::HelpRenameCategory => "Rename category",
        TextKey::HelpManageAliases => "Manage aliases",
        TextKey::HelpMergeCategories => "Merge categories",
        TextKey::HelpAliases => "Aliases",
        TextKey::HelpSwitchFocus => "Switch focus",
        TextKey::HelpDeleteAlias => "Delete alias",
        TextKey::HelpAddSave => "Add/Save",
        TextKey::HelpVault => "Vault",
        TextKey::HelpCreateVault => "Create vault",
        TextKey::HelpSelectVault => "Select vault",
        TextKey::HelpMembers => "Members",
        TextKey::HelpAddMember => "Add member",
        TextKey::HelpEditMember => "Edit member",
        TextKey::HelpRemoveMember => "Remove member",
        TextKey::HelpVaultMembers => "Vault members",
        TextKey::HelpFlowSharing => "Flow sharing",
        TextKey::HelpChangeFlow => "Change flow",
        TextKey::HelpChangeRole => "Change role",

        // Success Messages
        TextKey::SuccessCreated => "Created successfully",
        TextKey::SuccessUpdated => "Updated successfully",
        TextKey::SuccessDeleted => "Deleted successfully",
        TextKey::SuccessArchived => "Archived successfully",
        TextKey::SuccessVoided => "Voided successfully",
        TextKey::SuccessRefreshed => "Data refreshed",

        // Error Messages
        TextKey::ErrorGeneric => "An error occurred",
        TextKey::ErrorNetwork => "Connection error",
        TextKey::ErrorNotFound => "Not found",
        TextKey::ErrorUnauthorized => "Unauthorized",

        // Misc
        TextKey::MiscYes => "Yes",
        TextKey::MiscNo => "No",
        TextKey::MiscAll => "All",
        TextKey::MiscNone => "None",

        // Status bar
        TextKey::StatusOnline => "online",
        TextKey::StatusOffline => "offline",
    }
}
