use super::TextKey;

/// Returns the English translation for a text key.
#[must_use]
pub fn get(key: TextKey) -> &'static str {
    match key {
        // Sections
        TextKey::SectionHome => "Home",
        TextKey::SectionTransactions => "Transactions",
        TextKey::SectionWallets => "Wallets",
        TextKey::SectionFlows => "Flows",
        TextKey::SectionCategories => "Categories",
        TextKey::SectionMembers => "Members",
        TextKey::SectionVault => "Vault",
        TextKey::SectionPreferences => "Preferences",
        TextKey::SectionAccounts => "Accounts",
        TextKey::SectionAnalytics => "Analytics",
        TextKey::SectionSettings => "Settings",

        // Actions
        TextKey::ActionSave => "Save",

        // Hints - Footer Navigation
        TextKey::HintHome => "home",
        TextKey::HintTransactions => "txn",
        TextKey::HintAccounts => "accounts",
        TextKey::HintAnalytics => "analytics",
        TextKey::HintSettings => "settings",

        // Hints - Footer Actions
        TextKey::HintQuickAdd => "quick add",
        TextKey::HintHelp => "help",
        TextKey::HintCreate => "create",
        TextKey::HintEdit => "edit",
        TextKey::HintDelete => "delete",
        TextKey::HintSave => "save",
        TextKey::HintCancel => "cancel",
        TextKey::HintBack => "back",
        TextKey::HintRefresh => "refresh",
        TextKey::HintAdd => "add",
        TextKey::HintToggle => "toggle",
        TextKey::HintCategorize => "categorize",
        TextKey::HintExit => "exit",

        // Help Overlay
        TextKey::HelpTitle => "Keyboard Shortcuts",
        TextKey::HelpCloseHelp => "close help",
        TextKey::HelpGlobal => "Global",
        TextKey::HelpNavigation => "Navigation",
        TextKey::HelpCommonActions => "Common Actions",
        TextKey::HelpQuickAddTxn => "Quick add transaction",
        TextKey::HelpNewTxnModal => "New transaction (modal)",
        TextKey::HelpCommandPalette => "Command palette",
        TextKey::HelpSearch => "Search",
        TextKey::HelpShowHelp => "Show/hide help",
        TextKey::HelpNextSubTab => "Next sub-tab",
        TextKey::HelpPrevSubTab => "Prev sub-tab",
        TextKey::HelpNavigateList => "Navigate list",
        TextKey::HelpOpenDetails => "Open details",
        TextKey::HelpBackClose => "Back / Close",
        TextKey::HelpEditSelected => "Edit selected",
        TextKey::HelpDeleteSelected => "Delete selected",
        TextKey::HelpNavigateFeed => "Navigate feed",
        TextKey::HelpGoToTransactions => "Go to Transactions",
        TextKey::HelpGoToAccounts => "Go to Accounts",
        TextKey::HelpGoToAnalytics => "Go to Analytics",
        TextKey::HelpGoToSettings => "Go to Settings",
        TextKey::HelpNewIncome => "New income",
        TextKey::HelpNewRefund => "New refund",
        TextKey::HelpNewTransfer => "New transfer",
        TextKey::HelpToggleFilters => "Toggle filters",
        TextKey::HelpGroupTxns => "Group transactions",
        TextKey::HelpScopeWallet => "Scope to wallet",
        TextKey::HelpScopeFlow => "Scope to flow",
        TextKey::HelpClearFilters => "Clear filters",
        TextKey::HelpDeleteTxn => "Delete transaction",
        TextKey::HelpUndoDelete => "Undo delete (when shown)",
        TextKey::HelpToggleVoided => "Toggle voided",
        TextKey::HelpNextPrevPage => "Next/prev page",
        TextKey::HelpVisualMode => "Visual Mode",
        TextKey::HelpToggleVisual => "Toggle visual mode",
        TextKey::HelpSelectTxn => "Select transaction",
        TextKey::HelpExitVisual => "Exit visual mode",
        TextKey::HelpDetailView => "Detail View",
        TextKey::HelpEditTxn => "Edit transaction",
        TextKey::HelpRepeatTxn => "Repeat transaction",
        TextKey::HelpVoidTxn => "Void transaction",
        TextKey::HelpForm => "Form",
        TextKey::HelpNextField => "Next field",
        TextKey::HelpChangeValue => "Change value",
        TextKey::HelpFilters => "Filters",
        TextKey::HelpToggleType => "Toggle type",
        TextKey::HelpToggleScope => "Toggle scope",
        TextKey::HelpApply => "Apply",
        TextKey::HelpJumpSubTab => "Jump to sub-tab",
        TextKey::HelpSourcesWallets => "Sources (Wallets)",
        TextKey::HelpCreateWallet => "Create wallet",
        TextKey::HelpRenameWallet => "Rename wallet",
        TextKey::HelpDeleteArchive => "Delete (archive)",
        TextKey::HelpViewDetails => "View details",
        TextKey::HelpEnvelopesFlows => "Envelopes (Flows)",
        TextKey::HelpCreateEnvelope => "Create envelope",
        TextKey::HelpRenameEnvelope => "Rename envelope",
        TextKey::HelpChangeMode => "Change mode",
        TextKey::HelpRefreshData => "Refresh data",
        TextKey::HelpSwitchView => "Switch view",
        TextKey::HelpSwitchPanel => "Switch panel",
        TextKey::HelpCashSpendWorth => "Cash/Spend/Worth",
        TextKey::HelpChangePeriod => "Change period",
        TextKey::HelpCreateCategory => "Create category",
        TextKey::HelpRenameCategory => "Rename category",
        TextKey::HelpManageAliases => "Manage aliases",
        TextKey::HelpMergeCategories => "Merge categories",
        TextKey::HelpAliases => "Aliases",
        TextKey::HelpSwitchFocus => "Switch focus",
        TextKey::HelpDeleteAlias => "Delete alias",
        TextKey::HelpAddSave => "Add/Save",
        TextKey::HelpVault => "Vault",
        TextKey::HelpCreateVault => "Create vault",
        TextKey::HelpSelectVault => "Select vault",
        TextKey::HelpMembers => "Members",
        TextKey::HelpAddMember => "Add member",
        TextKey::HelpEditMember => "Edit member",
        TextKey::HelpRemoveMember => "Remove member",
        TextKey::HelpVaultMembers => "Vault members",
        TextKey::HelpFlowSharing => "Flow sharing",
        TextKey::HelpChangeFlow => "Change flow",
        TextKey::HelpChangeRole => "Change role",

        // Status bar
        TextKey::StatusOnline => "online",
        TextKey::StatusOffline => "offline",

        // Success Messages
        TextKey::SuccessTransactionSaved => "Transaction saved.",
        TextKey::SuccessTransactionUpdated => "Transaction updated.",
        TextKey::SuccessTransactionVoided => "Transaction voided.",
        TextKey::SuccessTransactionRepeated => "Transaction repeated.",
        TextKey::SuccessTransferWalletSaved => "Wallet transfer saved.",
        TextKey::SuccessTransferWalletUpdated => "Wallet transfer updated.",
        TextKey::SuccessTransferFlowSaved => "Flow transfer saved.",
        TextKey::SuccessTransferFlowUpdated => "Flow transfer updated.",
        TextKey::SuccessWalletCreated => "Wallet created.",
        TextKey::SuccessWalletUpdated => "Wallet updated.",
        TextKey::SuccessWalletRestored => "Wallet restored.",
        TextKey::SuccessFlowCreated => "Flow created.",
        TextKey::SuccessFlowUpdated => "Flow updated.",
        TextKey::SuccessFlowRestored => "Flow restored.",
        TextKey::SuccessCategoryCreated => "Category created.",
        TextKey::SuccessCategoryUpdated => "Category updated.",
        TextKey::SuccessAliasCreated => "Alias created.",
        TextKey::SuccessAliasDeleted => "Alias deleted.",
        TextKey::SuccessVaultCreated => "Vault created.",
        TextKey::SuccessVaultSelected => "Vault selected.",
        TextKey::SuccessDefaultsSaved => "Defaults saved.",
        TextKey::SuccessMergeCompleted => "Merge completed.",
        TextKey::SuccessMergePreviewOk => "Preview ok. Press Enter to confirm.",
        TextKey::SuccessDeletedItem => "Deleted \"{label}\" ({amount})",
        TextKey::SuccessDeletedMultiple => "Deleted {count} transactions",
        TextKey::SuccessCategorizedTransactions => {
            "Categorized {count} transactions as #{category}"
        }
        TextKey::SuccessDeletedWallet => "Deleted \"{name}\"",
        TextKey::SuccessDeletedFlow => "Deleted \"{name}\"",

        // Error Messages
        TextKey::ErrorSaving => "Error saving.",
        TextKey::ErrorUpdating => "Error updating.",
        TextKey::ErrorVoiding => "Error voiding transaction.",
        TextKey::ErrorRepeating => "Error repeating transaction.",
        TextKey::ErrorConnection => "Connection error",
        TextKey::ErrorTransferWallet => "Wallet transfer error.",
        TextKey::ErrorTransferFlow => "Flow transfer error.",
        TextKey::ErrorCreateWallet => "Failed to create wallet.",
        TextKey::ErrorUpdateWallet => "Failed to update wallet.",
        TextKey::ErrorArchiveWallet => "Error archiving wallet.",
        TextKey::ErrorRestoreWallet => "Error restoring wallet.",
        TextKey::ErrorCreateFlow => "Failed to create flow.",
        TextKey::ErrorUpdateFlow => "Failed to update flow.",
        TextKey::ErrorArchiveFlow => "Failed to archive flow.",
        TextKey::ErrorRestoreFlow => "Error restoring flow.",
        TextKey::ErrorCreateCategory => "Error creating category.",
        TextKey::ErrorUpdateCategory => "Error updating category.",
        TextKey::ErrorArchiveCategory => "Error archiving category.",
        TextKey::ErrorCreateAlias => "Error creating alias.",
        TextKey::ErrorDeleteAlias => "Error deleting alias.",
        TextKey::ErrorCreateVault => "Error creating vault.",
        TextKey::ErrorDeleteVault => "Error deleting vault.",
        TextKey::ErrorSaveDefaults => "Error saving defaults.",
        TextKey::ErrorInvalidCredentials => "Invalid credentials or missing pairing.",
        TextKey::ErrorMembershipLastOwner => "Cannot remove the last owner of the flow.",
        TextKey::ErrorMembershipOwnerImmutable => "Cannot change the vault owner's role.",
        TextKey::ErrorMembershipOwnerRemoveForbidden => "Cannot remove the vault owner.",
        TextKey::ErrorOperationForbidden => "Operation not permitted.",
        TextKey::ErrorResourceNotFound => "Resource not found.",
        TextKey::ErrorConflict => "Conflict: {message}",
        TextKey::ErrorValidation => "Validation error: {message}",
        TextKey::ErrorValidationAmbiguousVault => {
            "Vault name is ambiguous. Use \"Main (owner)\" or a vault id."
        }
        TextKey::ErrorBadRequest => "Bad request: {message}",
        TextKey::ErrorServerError => "Server error: {message}",
        TextKey::ErrorServerUnreachable => "Server unreachable: {error}",

        // State Messages
        TextKey::StateSnapshotUnavailable => "Snapshot unavailable.",
        TextKey::StateVaultUnavailable => "Vault unavailable.",
        TextKey::StateUserUnavailable => "User unavailable.",
        TextKey::StateNoWalletAvailable => "No wallet available.",
        TextKey::StateUnallocatedMissing => "Unallocated flow missing.",
        TextKey::StateCannotDetermineWalletTransfer => "Cannot determine transfer wallets.",
        TextKey::StateCannotDetermineFlowTransfer => "Cannot determine transfer flows.",

        // UI Labels
        TextKey::UiOther => "Other",
        TextKey::UiError => "Error",
        TextKey::UiFailedToDeleteVault => "Failed to delete vault.",
        TextKey::UiNoDetailAvailable => "No detail available.",
        TextKey::UiNoElement => "No element.",
        TextKey::UiNoRecentCategories => "No recent categories.",
        TextKey::UiRecentCategories => "Recent categories",

        // Prompts and Hints
        TextKey::PromptEnterName => "Enter a name.",
        TextKey::PromptEnterUsername => "Enter a username.",
        TextKey::PromptEnterAlias => "Enter an alias.",
        TextKey::PromptEnterCap => "Enter a cap.",
        TextKey::PromptFillAllFields => "Fill all fields.",
        TextKey::PromptUseDedicatedTransferForm => "Use the dedicated transfer form.",
        TextKey::PromptAtLeastTwoCategories => "At least 2 categories required to merge.",
        TextKey::PromptSourceCategoryInvalid => "Source category invalid.",
        TextKey::PromptDestinationCategoryInvalid => "Destination category invalid.",
        TextKey::PromptCheckConflicts => "Invalid merge. Check conflicts.",
        TextKey::PromptNoShareableFlows => "No shareable flows.",
        TextKey::PromptNoMemberSelected => "No member selected.",
        TextKey::PromptNoAliasSelected => "No alias selected.",
        TextKey::PromptNoCategorySelected => "No category selected.",
        TextKey::PromptEnterCategory => "Enter a category.",

        // Quick Add / Parsing Errors
        TextKey::QuickAddEnterAmount => "Enter an amount.",
        TextKey::QuickAddAmountMissing => "Amount missing.",
        TextKey::QuickAddAmountInvalid => "Invalid amount.",
        TextKey::QuickAddAmountMustBePositive => "Amount must be > 0.",
        TextKey::QuickAddTooManyCategories => "Too many tags: maximum 1.",
        TextKey::QuickAddTooManyWallets => "Too many wallets: maximum 1.",
        TextKey::QuickAddTooManyEnvelopes => "Too many envelopes: maximum 1.",
        TextKey::QuickAddSpecifyTwoWallets => "Specify exactly 2 wallets (@from @to).",
        TextKey::QuickAddSpecifyTwoFlows => "Specify exactly 2 flows (>from >to).",
        TextKey::QuickAddWalletNotFound => "Wallet not found: @{query}",
        TextKey::QuickAddEnvelopeNotFound => "Envelope not found: >{query}",
        TextKey::QuickAddFlowNotFound => "Flow not found: >{query}",
        TextKey::QuickAddWalletsMustBeDifferent => "The two wallets must be different.",
        TextKey::QuickAddFlowsMustBeDifferent => "The two flows must be different.",

        // Validation Errors
        TextKey::ValidationRequired => "Required field",
        TextKey::ValidationAmountRequired => "Amount required",
        TextKey::ValidationAmountInvalid => "Invalid amount",
        TextKey::ValidationAmountPositive => "Amount must be positive",
        TextKey::ValidationDateRequired => "Date required",
        TextKey::ValidationDateInvalid => "Invalid date format (YYYY-MM-DD HH:MM)",
        TextKey::ValidationDateInvalidTimezone => "Invalid timezone",
        TextKey::ValidationLengthMin => "Minimum {min} characters",
        TextKey::ValidationLengthMax => "Maximum {max} characters",
        TextKey::ValidationTransferSameSource => "Choose two different wallets.",
        TextKey::ValidationTransferSameDestination => "Choose two different flows.",
        TextKey::ValidationTransferSameElements => "Choose two different elements.",
        TextKey::ValidationTransferMinimumTwo => "At least 2 elements required.",
        TextKey::ValidationWalletInvalid => "Invalid wallet.",
        TextKey::ValidationFlowInvalid => "Invalid flow.",
        TextKey::ValidationCategoryInvalid => "Invalid category.",
        TextKey::ValidationOpeningBalanceInvalid => "Invalid opening balance.",
        TextKey::ValidationCapInvalid => "Invalid cap.",
        TextKey::ValidationCapMustBePositive => "Cap must be > 0.",
        TextKey::ValidationOpeningBalanceNonNegative => "Opening allocation must be >= 0.",
        TextKey::ValidationNoWalletSelected => "No wallet selected.",
        TextKey::ValidationNoFlowSelected => "No flow selected.",
        TextKey::ValidationNoTransactionToVoid => "No transaction to void.",
        TextKey::ValidationUnallocatedCannotRename => "Unallocated cannot be renamed.",
        TextKey::ValidationUnallocatedCannotArchive => "Unallocated cannot be archived.",
        TextKey::ValidationAlreadyArchived => "Already archived.",
        TextKey::ValidationSystemCategoryImmutable => "System categories cannot be modified.",
        TextKey::ValidationNoTransactionSelected => "No transaction selected.",
        TextKey::ValidationNoWalletAvailable => "No wallet available.",
        TextKey::ValidationNoFlowAvailable => "No flow available.",
        TextKey::ValidationNoElementAvailable => "No element available.",
        TextKey::ValidationTransactionVoided => "Voided transaction: editing not available.",
        TextKey::ValidationTransactionInvalid => "Invalid transaction.",
        TextKey::ValidationTransferWalletInvalid => "Invalid wallet transfer.",
        TextKey::ValidationTransferFlowInvalid => "Invalid flow transfer.",
        TextKey::ValidationWalletArchived => "Archived wallet: editing not available.",
        TextKey::ValidationFlowArchived => "Archived flow: editing not available.",
        TextKey::ValidationSnapshotUnavailable => "Snapshot unavailable.",

        // Home screen stat cards
        TextKey::HomeCardIncome => "Income",
        TextKey::HomeCardExpenses => "Expenses",
        TextKey::HomeCardThisMonth => "this month",

        // Dialog titles and messages
        TextKey::DialogUnsavedChangesTitle => "Unsaved Changes",
        TextKey::DialogUnsavedChangesMessage => "You have unsaved changes. Discard them?",
        TextKey::DialogSave => "Save",
        TextKey::DialogDiscard => "Discard",
        TextKey::DialogDelete => "Delete",
        TextKey::DialogDeleteVaultTitle => "Delete Vault",
        TextKey::DialogDeleteVaultWarning => "This action cannot be undone.",
        TextKey::DialogDeleteTransactionsTitle => "Delete Transactions",
        TextKey::DialogDeleteTransactionTitle => "Delete Transaction",
        TextKey::DialogDeleteUndoHint => "You can undo this action for 5 seconds.",
        TextKey::DialogDeleteWalletTitle => "Delete Wallet",
        TextKey::DialogDeleteWalletHint => "The wallet will be hidden but can be restored later.",
        TextKey::DialogDeleteFlowTitle => "Delete Flow",
        TextKey::DialogDeleteFlowHint => "The flow will be hidden but can be restored later.",
        TextKey::DialogDeleteCategoryTitle => "Delete Category",
        TextKey::DialogDeleteCategoryHint => {
            "The category will be hidden but can be restored later."
        }
        TextKey::DialogThisVault => "this vault",
        TextKey::DialogTransaction => "Transaction",
        TextKey::DialogConnectionErrorTitle => "Connection Error",
        TextKey::DialogConnectionErrorMessage => "Unable to connect to server.",

        // Form field labels
        TextKey::FormAmount => "Amount",
        TextKey::FormWallet => "Wallet",
        TextKey::FormFlow => "Flow",
        TextKey::FormCategory => "Category",
        TextKey::FormNote => "Note",
        TextKey::FormWhen => "When",

        // Form field helpers
        TextKey::FormHelperAmount => "Enter numerical amount (required)",
        TextKey::FormHelperWallet => "Source/destination wallet",
        TextKey::FormHelperFlow => "Envelope/budget allocation",
        TextKey::FormHelperCategory => "Tag for analytics",
        TextKey::FormHelperNote => "Optional description",
        TextKey::FormHelperWhen => "Date & time (default: now)",

        // Form titles
        TextKey::FormEditIncome => "Edit Income",
        TextKey::FormNewIncome => "New Income",
        TextKey::FormEditExpense => "Edit Expense",
        TextKey::FormNewExpense => "New Expense",
        TextKey::FormEditRefund => "Edit Refund",
        TextKey::FormNewRefund => "New Refund",
        TextKey::FormEditTransaction => "Edit Transaction",
        TextKey::FormNewTransaction => "New Transaction",

        // Form footer hints
        TextKey::FormHintSave => " Save  ",
        TextKey::FormHintCancel => " Cancel  ",
        TextKey::FormHintNextField => " Next field  ",
        TextKey::FormHintCycleChoices => " Cycle choices",

        // Transaction list / common labels
        TextKey::TxnScopeAll => "All",
        TextKey::TxnUncategorized => "Uncategorized",
        TextKey::TxnNoWallet => "No wallet",
        TextKey::TxnNoEnvelope => "No envelope",
        TextKey::TxnRecentsPrefix => "Recents: ",
        TextKey::TxnRecentsCategories => "Categories: ",
        TextKey::TxnRecentsWallet => "Wallet: ",
        TextKey::TxnRecentsFlow => "Flow: ",

        // Quick add
        TextKey::QuickAddTitle => " Quick Add ",
        TextKey::QuickAddPlaceholder => "Press [n] to add transaction...",
        TextKey::QuickAddToday => "Today",
        TextKey::QuickAddSyntaxHint => {
            "Syntax: [+]amount note [#cat] [@wallet] [>envelope]  |  + income, r refund"
        }
        TextKey::QuickAddSyntaxShort => "[+]amount note [#category] [@wallet] [>envelope]",
        TextKey::QuickAddExamples => "   Examples: ",
        TextKey::QuickAddEnvelopeSuggestions => "Envelope suggestions: ",
        TextKey::QuickAddCycle => " cycle",

        // Stats labels
        TextKey::StatsTitle => "Stats",
        TextKey::StatsNoData => "No data. Press ",
        TextKey::StatsRefreshHint => " to refresh.",
        TextKey::StatsMonthSummary => "Month Summary",
        TextKey::StatsMoM => "MoM",
        TextKey::StatsInc => "Inc",
        TextKey::StatsExp => "Exp",
        TextKey::StatsNa => "n/a",
        TextKey::StatsIncome => "Income",
        TextKey::StatsExpenses => "Expenses",
        TextKey::StatsExpenseOverIncome => "Expense/Income",
        TextKey::StatsNoIncomeToCompare => "No income to compare",
        TextKey::StatsNet => "Net",
        TextKey::StatsBalance => "Balance",
        TextKey::StatsCategoryBreakdown => "Category Breakdown",
        TextKey::StatsNoCategoryData => "No expense data for category breakdown",
        TextKey::StatsDistribution => "Distribution",
        TextKey::StatsBalanceTrend => "Balance Trend (30d)",
        TextKey::StatsMonthlyTrend => "Monthly Trend",
        TextKey::StatsMonthlyTrendNoData => {
            "Monthly trend data not available. Press 'r' to refresh stats."
        }
        TextKey::StatsFinancialTrends => "Financial Trends (6 months)",
        TextKey::StatsNetSavings => "Net Savings",
        TextKey::StatsTotalIncome => "Total Income",
        TextKey::StatsTotalExpenses => "Total Expenses",
        TextKey::StatsNetBalance => "Net Balance",
        TextKey::StatsThisMonth => "This month",
        TextKey::StatsExpenseTrend => "Expense Trend (6m)",
        TextKey::StatsNoExpenseData => "No expense trend data. Press 'r' to refresh.",
        TextKey::StatsTabCashFlow => "1 Cash Flow",
        TextKey::StatsTabSpending => "2 Spending",
        TextKey::StatsTabNetWorth => "3 Net Worth",

        // Category screen labels
        TextKey::CatTitle => " Categories ",
        TextKey::CatNoCategoriesYet => "No categories yet",
        TextKey::CatCreateFirst => " to create your first category",
        TextKey::CatRenameTitle => "Rename Category",
        TextKey::CatCurrentLabel => "Current:",
        TextKey::CatNewNameLabel => "New name:",
        TextKey::CatAliasesFor => " Aliases for {} ",
        TextKey::CatNoAliasesForCategory => "No aliases for this category",
        TextKey::CatTypeToAddAlias => "Type in the input below to add one",
        TextKey::CatNewAlias => "  New alias: ",
        TextKey::CatSwitchFocus => " switch focus  ",
        TextKey::CatAliasesTitle => " Aliases ",
        TextKey::CatNoCategorySelected => "No category selected",
        TextKey::CatCategoryLabel => "  Category: ",
        TextKey::CatPressToLoadAliases => "  Press [l] to load aliases",
        TextKey::CatNoAliases => "  No aliases",
        TextKey::CatMore => "    ... +{} more",
        TextKey::CatNewCategoryTitle => " New Category ",
        TextKey::CatMergeCategoriesTitle => " Merge Categories ",
        TextKey::CatMergeLabel => "  Merge: ",
        TextKey::CatMergePreviewOkMerge => "Preview OK. Press [Enter] to merge.",
        TextKey::CatMergePreviewOkConfirm => "Preview OK. Press [Enter] to confirm.",
        TextKey::CatMergeConflicts => "  Conflicts:",
        TextKey::CatMergeSelectTarget => "  Select target and press [Enter] for preview",
        TextKey::CatMergePreviewAction => " preview/merge  ",
        TextKey::CatConflictSameCategory => "Cannot merge category with itself",
        TextKey::CatConflictSourceSystem => "System category: {value}",
        TextKey::CatConflictTargetArchived => "Target is archived: {value}",
        TextKey::CatConflictAliasConflict => "Alias conflict: {value}",
        TextKey::CatConflictNameConflict => "Name conflict: {value}",
        TextKey::CatConflictGeneric => "Conflict: {kind} ({value})",

        // Category list badges
        TextKey::CatBadgeSystem => "[system]",
        TextKey::CatBadgeArchived => "[archived]",
        TextKey::CatBadgeFrom => "[FROM]",
        TextKey::CatBadgeTo => "[TO]",

        // Category form hints
        TextKey::CatHintCreate => " create  ",
        TextKey::CatHintRename => " rename  ",
        TextKey::CatHintAliases => " aliases  ",
        TextKey::CatHintMerge => " merge",

        // Transaction header / grouping
        TextKey::TxnGroupDate => "Date",
        TextKey::TxnGroupCategory => "Category",
        TextKey::TxnGroupWallet => "Wallet",
        TextKey::TxnGroupEnvelope => "Envelope",
        TextKey::TxnHeaderFiltersOff => "Filters [off]",
        TextKey::TxnHeaderSearch => "Search: ",

        // Transaction detail
        TextKey::TxnDetailTitle => "Transaction Detail",
        TextKey::TxnDetailKind => "Kind",
        TextKey::TxnDetailVoided => "Voided",
        TextKey::TxnDetailVoidedYes => "YES",
        TextKey::TxnDetailVoidedNo => "NO",
        TextKey::TxnDetailWhen => "When",
        TextKey::TxnDetailAmount => "Amount",
        TextKey::TxnDetailCategory => "Category",
        TextKey::TxnDetailNote => "Note",
        TextKey::TxnDetailLegsTitle => "Legs",
        TextKey::TxnDetailLegWallet => "Wallet",
        TextKey::TxnDetailLegFlow => "Flow",

        // Vault view / defaults
        TextKey::VaultDefaultName => "Main",
        TextKey::VaultQuickDefaults => "Quick Defaults",
        TextKey::VaultDefaultWallet => "Default Wallet",
        TextKey::VaultDefaultFlow => "Default Flow",
        TextKey::VaultIdLabel => "ID",
        TextKey::VaultCurrencyLabel => "Currency",

        // Loading & empty states
        TextKey::LoadingGeneric => "Loading...",
        TextKey::LoadingVaultData => "Fetching vault data",
        TextKey::SearchLabel => "Search: ",
        TextKey::SearchNoResults => "No results for ",
        TextKey::SearchClearHint => "[Esc] to clear search",
        TextKey::SearchClearShort => "[Esc] clear",

        // Date labels
        TextKey::DateToday => "Today",
        TextKey::DateYesterday => "Yesterday",

        // Entity list shared
        TextKey::EntityArchivedOn => "Archived: On",
        TextKey::EntityBadgeArchived => "[archived]",
        TextKey::EntityBadgeDefault => "[default]",

        // Wallet screen
        TextKey::WalletTitle => " Wallets ",
        TextKey::WalletDetailTitle => "Wallet Detail",
        TextKey::WalletNotFound => "Wallet not found",
        TextKey::WalletSelectPrompt => "Select a wallet to view details",
        TextKey::WalletNoTransactions => "No transactions for this wallet",
        TextKey::WalletWelcomeTitle => "\u{1f4b0} Welcome!",
        TextKey::WalletWelcomeDesc1 => "Let's create your first wallet to start",
        TextKey::WalletWelcomeDesc2 => "tracking your finances.",
        TextKey::WalletHintQuickCreate => " Quick create  ",
        TextKey::WalletHintCreateDetails => " Create with details",
        TextKey::FormTitleRenameWallet => "Rename Wallet",
        TextKey::FormTitleNewWallet => "New Wallet",

        // Flow screen
        TextKey::FlowTitle => " Budgets & Goals ",
        TextKey::FlowDetailTitle => "Flow Detail",
        TextKey::FlowNotFound => "Flow not found",
        TextKey::FlowSelectPrompt => "Select a flow to view details",
        TextKey::FlowNoTransactions => "No transactions for this flow",
        TextKey::FlowWelcomeTitle => "\u{1f4e6} Budget with Envelopes",
        TextKey::FlowWelcomeDesc1 => "Create envelopes to organize and track",
        TextKey::FlowWelcomeDesc2 => "spending by category or goal.",
        TextKey::FlowHintQuickCreate => " Quick create  ",
        TextKey::FlowHintCreateCap => " Create with cap",
        TextKey::FormTitleRenameFlow => "Rename Flow",
        TextKey::FormTitleNewFlow => "New Budget/Goal",

        // Home screen
        TextKey::HomeActivityFeed => "Activity Feed",
        TextKey::HomeNetWorth => "Net Worth",
        TextKey::HomeQuickBalances => "Balances",
        TextKey::HomeNoDataYet => "No data yet",
        TextKey::HomeAddFirstTxn => "[n] to add your first transaction",
        TextKey::HomeWallets => "Wallets",
        TextKey::HomeBudgets => "Budgets",
        TextKey::HomeNoActivityYet => "No activity yet",

        // Settings
        TextKey::SettingsCardTitle => "Settings",
        TextKey::PreferencesTitle => "Preferences",

        // Members
        TextKey::MembersVaultTitle => "Vault Members",
        TextKey::MembersEditTitle => "Edit Member",
        TextKey::MembersAddTitle => "Add Member",

        // Vault
        TextKey::VaultCreateTitle => "Create Vault",

        // Transfers & pickers
        TextKey::TransferWalletTitle => "Transfer Wallet",
        TextKey::TransferFlowTitle => "Transfer Flow",
        TextKey::TransferEditWalletTitle => "Edit Transfer Wallet",
        TextKey::TransferEditFlowTitle => "Edit Transfer Flow",
        TextKey::TransferTypeTitle => "Transfer Type",
        TextKey::TransferFrom => "From",
        TextKey::TransferTo => "To",
        TextKey::TransferAvailable => "Available",
        TextKey::TransferBadgeFrom => " [from]",
        TextKey::TransferBadgeTo => " [to]",
        TextKey::TransferFormHints => {
            "Tab: next \u{2022} \u{2191}/\u{2193}: change \u{2022} Enter: save \u{2022} Esc: cancel"
        }

        // Filters
        TextKey::FilterTitle => " Filters ",
        TextKey::FilterFrom => "From",
        TextKey::FilterTo => "To",
        TextKey::FilterTransactionTypes => "Transaction Types ",
        TextKey::FilterToggleHint => "(press key to toggle)",
        TextKey::FilterKindIncome => "Income",
        TextKey::FilterKindExpense => "Expense",
        TextKey::FilterKindRefund => "Refund",
        TextKey::FilterKindWalletTransfer => "Wallet Transfer",
        TextKey::FilterKindFlowTransfer => "Flow Transfer",

        // Pickers
        TextKey::PickerAllWallets => "All wallets",
        TextKey::PickerAllFlows => "All flows",
        TextKey::PickerSelectWallet => "Select wallet scope",
        TextKey::PickerSelectFlow => "Select flow scope",
        TextKey::PickerBadgeUnallocated => " [Unallocated]",
        TextKey::PickerSuffixArchived => " (archived)",

        // Grouping dialog
        TextKey::GroupingTitle => " Group Transactions ",
        TextKey::GroupingDate => "Date",
        TextKey::GroupingCategory => "Category",
        TextKey::GroupingWallet => "Wallet",
        TextKey::GroupingEnvelope => "Envelope",
        TextKey::GroupingCurrent => "current",

        // Transactions list
        TextKey::TxnNoTransactionsYet => "No transactions yet. Press ",
        TextKey::TxnAddOneHint => " to add one.",
        TextKey::TxnSearchEditClearHint => "Ctrl+F to edit \u{2022} Esc to clear",

        // Scope labels (transaction common)
        TextKey::ScopeFlowLabel => "Flow: ",
        TextKey::ScopeFlowUnknown => "Flow: ?",
        TextKey::ScopeWalletLabel => "Wallet: ",
        TextKey::ScopeWalletUnknown => "Wallet: ?",

        // Shell / Status
        TextKey::ShellVaultLabel => "Vault",
        TextKey::ShellUserLabel => "User",
        TextKey::ShellVaultFallback => "Main",

        // Error dialog
        TextKey::ErrorTechnicalDetails => "Technical details:",

        // Flow form
        TextKey::FormLabelAllowNegative => "Allow negative",
        TextKey::FlowBadgeAllowNegative => "[allow neg.]",

        // Recurring
        TextKey::RecurringTitle => "Recurring",
        TextKey::RecurringEmpty => "No recurring templates",
        TextKey::RecurringPending => "Pending approval",
        TextKey::RecurringFreqDaily => "Daily",
        TextKey::RecurringFreqWeekly => "Weekly",
        TextKey::RecurringFreqMonthly => "Monthly",
        TextKey::RecurringFreqYearly => "Yearly",
        TextKey::RecurringFormTitle => "New Recurring",
        TextKey::RecurringFormEditTitle => "Edit Recurring",
        TextKey::RecurringFormKind => "Kind",
        TextKey::RecurringFormAmount => "Amount",
        TextKey::RecurringFormFrequency => "Frequency",
        TextKey::RecurringFormDay => "Day of period",
        TextKey::RecurringFormStartDate => "Start date",
        TextKey::RecurringFormEndDate => "End date",
        TextKey::RecurringKindIncome => "Income",
        TextKey::RecurringKindExpense => "Expense",
        TextKey::RecurringEnabled => "on",
        TextKey::RecurringDisabled => "off",
        TextKey::RecurringCreated => "Recurring template created.",
        TextKey::RecurringUpdated => "Recurring template updated.",
        TextKey::RecurringArchived => "Recurring template archived.",
        TextKey::RecurringExecuted => "Recurring transaction executed.",

        // General UI
        TextKey::UiNone => "None",
        TextKey::UiUndoApplied => "Undo applied.",
        TextKey::UiYes => "Yes",
        TextKey::UiNo => "No",
    }
}
