use super::TextKey;

/// Returns the Italian translation for a text key.
#[must_use]
pub fn get(key: TextKey) -> &'static str {
    match key {
        // Sections
        TextKey::SectionHome => "Home",
        TextKey::SectionTransactions => "Transazioni",
        TextKey::SectionWallets => "Portafogli",
        TextKey::SectionFlows => "Flussi",
        TextKey::SectionCategories => "Categorie",
        TextKey::SectionMembers => "Membri",
        TextKey::SectionVault => "Vault",
        TextKey::SectionPreferences => "Preferenze",
        TextKey::SectionAccounts => "Conti",
        TextKey::SectionAnalytics => "Statistiche",
        TextKey::SectionSettings => "Impostazioni",

        // Actions
        TextKey::ActionSave => "Salva",

        // Hints - Footer Navigation
        TextKey::HintHome => "home",
        TextKey::HintTransactions => "txn",
        TextKey::HintAccounts => "conti",
        TextKey::HintAnalytics => "statistiche",
        TextKey::HintSettings => "impostazioni",

        // Hints - Footer Actions
        TextKey::HintQuickAdd => "aggiungi",
        TextKey::HintHelp => "aiuto",
        TextKey::HintCreate => "crea",
        TextKey::HintEdit => "modifica",
        TextKey::HintDelete => "elimina",
        TextKey::HintSave => "salva",
        TextKey::HintCancel => "annulla",
        TextKey::HintBack => "indietro",
        TextKey::HintRefresh => "aggiorna",
        TextKey::HintAdd => "aggiungi",
        TextKey::HintToggle => "seleziona",
        TextKey::HintCategorize => "categorizza",
        TextKey::HintExit => "esci",

        // Help Overlay
        TextKey::HelpTitle => "Scorciatoie da Tastiera",
        TextKey::HelpCloseHelp => "chiudi aiuto",
        TextKey::HelpGlobal => "Globale",
        TextKey::HelpNavigation => "Navigazione",
        TextKey::HelpCommonActions => "Azioni Comuni",
        TextKey::HelpQuickAddTxn => "Aggiungi transazione veloce",
        TextKey::HelpNewTxnModal => "Nuova transazione (modale)",
        TextKey::HelpCommandPalette => "Palette comandi",
        TextKey::HelpSearch => "Cerca",
        TextKey::HelpShowHelp => "Mostra/nascondi aiuto",
        TextKey::HelpNextSubTab => "Tab successivo",
        TextKey::HelpPrevSubTab => "Tab precedente",
        TextKey::HelpNavigateList => "Naviga lista",
        TextKey::HelpOpenDetails => "Apri dettagli",
        TextKey::HelpBackClose => "Indietro / Chiudi",
        TextKey::HelpEditSelected => "Modifica selezionato",
        TextKey::HelpDeleteSelected => "Elimina selezionato",
        TextKey::HelpNavigateFeed => "Naviga feed",
        TextKey::HelpGoToTransactions => "Vai a Transazioni",
        TextKey::HelpGoToAccounts => "Vai a Conti",
        TextKey::HelpGoToAnalytics => "Vai a Statistiche",
        TextKey::HelpGoToSettings => "Vai a Impostazioni",
        TextKey::HelpNewIncome => "Nuova entrata",
        TextKey::HelpNewRefund => "Nuovo rimborso",
        TextKey::HelpNewTransfer => "Nuovo trasferimento",
        TextKey::HelpToggleFilters => "Mostra/nascondi filtri",
        TextKey::HelpGroupTxns => "Raggruppa transazioni",
        TextKey::HelpScopeWallet => "Filtra per portafoglio",
        TextKey::HelpScopeFlow => "Filtra per flusso",
        TextKey::HelpClearFilters => "Rimuovi filtri",
        TextKey::HelpDeleteTxn => "Elimina transazione",
        TextKey::HelpUndoDelete => "Annulla eliminazione (se visibile)",
        TextKey::HelpToggleVoided => "Mostra/nascondi annullate",
        TextKey::HelpNextPrevPage => "Pagina succ./prec.",
        TextKey::HelpVisualMode => "Modalita' Visuale",
        TextKey::HelpToggleVisual => "Attiva modalita' visuale",
        TextKey::HelpSelectTxn => "Seleziona transazione",
        TextKey::HelpExitVisual => "Esci modalita' visuale",
        TextKey::HelpDetailView => "Vista Dettaglio",
        TextKey::HelpEditTxn => "Modifica transazione",
        TextKey::HelpRepeatTxn => "Ripeti transazione",
        TextKey::HelpVoidTxn => "Annulla transazione",
        TextKey::HelpForm => "Modulo",
        TextKey::HelpNextField => "Campo successivo",
        TextKey::HelpChangeValue => "Cambia valore",
        TextKey::HelpFilters => "Filtri",
        TextKey::HelpToggleType => "Cambia tipo",
        TextKey::HelpToggleScope => "Cambia ambito",
        TextKey::HelpApply => "Applica",
        TextKey::HelpJumpSubTab => "Vai a sub-tab",
        TextKey::HelpSourcesWallets => "Fonti (Portafogli)",
        TextKey::HelpCreateWallet => "Crea portafoglio",
        TextKey::HelpRenameWallet => "Rinomina portafoglio",
        TextKey::HelpDeleteArchive => "Elimina (archivia)",
        TextKey::HelpViewDetails => "Visualizza dettagli",
        TextKey::HelpEnvelopesFlows => "Buste (Flussi)",
        TextKey::HelpCreateEnvelope => "Crea busta",
        TextKey::HelpRenameEnvelope => "Rinomina busta",
        TextKey::HelpChangeMode => "Cambia modalita'",
        TextKey::HelpGoals => "Obiettivi",
        TextKey::HelpComingSoon => "(in arrivo)",
        TextKey::HelpRefreshData => "Aggiorna dati",
        TextKey::HelpSwitchView => "Cambia vista",
        TextKey::HelpCashSpendWorth => "Cassa/Spese/Patrimonio",
        TextKey::HelpChangePeriod => "Cambia periodo",
        TextKey::HelpCreateCategory => "Crea categoria",
        TextKey::HelpRenameCategory => "Rinomina categoria",
        TextKey::HelpManageAliases => "Gestisci alias",
        TextKey::HelpMergeCategories => "Unisci categorie",
        TextKey::HelpAliases => "Alias",
        TextKey::HelpSwitchFocus => "Cambia focus",
        TextKey::HelpDeleteAlias => "Elimina alias",
        TextKey::HelpAddSave => "Aggiungi/Salva",
        TextKey::HelpVault => "Vault",
        TextKey::HelpCreateVault => "Crea vault",
        TextKey::HelpSelectVault => "Seleziona vault",
        TextKey::HelpMembers => "Membri",
        TextKey::HelpAddMember => "Aggiungi membro",
        TextKey::HelpEditMember => "Modifica membro",
        TextKey::HelpRemoveMember => "Rimuovi membro",
        TextKey::HelpVaultMembers => "Membri vault",
        TextKey::HelpFlowSharing => "Condivisione flusso",
        TextKey::HelpChangeFlow => "Cambia flusso",
        TextKey::HelpChangeRole => "Cambia ruolo",

        // Status bar
        TextKey::StatusOnline => "online",
        TextKey::StatusOffline => "offline",

        // Success Messages
        TextKey::SuccessTransactionSaved => "Transazione salvata.",
        TextKey::SuccessTransactionUpdated => "Transazione aggiornata.",
        TextKey::SuccessTransactionVoided => "Transazione annullata.",
        TextKey::SuccessTransactionRepeated => "Transazione ripetuta.",
        TextKey::SuccessTransferWalletSaved => "Transfer wallet salvato.",
        TextKey::SuccessTransferWalletUpdated => "Transfer wallet aggiornato.",
        TextKey::SuccessTransferFlowSaved => "Transfer flow salvato.",
        TextKey::SuccessTransferFlowUpdated => "Transfer flow aggiornato.",
        TextKey::SuccessWalletCreated => "Wallet creato.",
        TextKey::SuccessWalletUpdated => "Wallet aggiornato.",
        TextKey::SuccessWalletRestored => "Wallet ripristinato.",
        TextKey::SuccessFlowCreated => "Flow creato.",
        TextKey::SuccessFlowUpdated => "Flow aggiornato.",
        TextKey::SuccessFlowRestored => "Flow ripristinato.",
        TextKey::SuccessCategoryCreated => "Categoria creata.",
        TextKey::SuccessCategoryUpdated => "Categoria aggiornata.",
        TextKey::SuccessAliasCreated => "Alias creato.",
        TextKey::SuccessAliasDeleted => "Alias eliminato.",
        TextKey::SuccessVaultCreated => "Vault creato.",
        TextKey::SuccessVaultSelected => "Vault selected.",
        TextKey::SuccessDefaultsSaved => "Default salvati.",
        TextKey::SuccessMergeCompleted => "Merge completato.",
        TextKey::SuccessMergePreviewOk => "Preview ok. Premi Enter per confermare.",
        TextKey::SuccessDeletedItem => "Eliminato \"{label}\" ({amount})",
        TextKey::SuccessDeletedMultiple => "Eliminate {count} transazioni",
        TextKey::SuccessCategorizedTransactions => "Categorizzate {count} transazioni come #{category}",
        TextKey::SuccessDeletedWallet => "Eliminato \"{name}\"",
        TextKey::SuccessDeletedFlow => "Eliminato \"{name}\"",

        // Error Messages
        TextKey::ErrorSaving => "Errore salvataggio.",
        TextKey::ErrorUpdating => "Errore aggiornamento.",
        TextKey::ErrorVoiding => "Errore durante l'annullamento.",
        TextKey::ErrorRepeating => "Errore durante la ripetizione.",
        TextKey::ErrorConnection => "Errore connessione",
        TextKey::ErrorTransferWallet => "Errore transfer wallet.",
        TextKey::ErrorTransferFlow => "Errore transfer flow.",
        TextKey::ErrorCreateWallet => "Errore creazione wallet.",
        TextKey::ErrorUpdateWallet => "Errore aggiornamento wallet.",
        TextKey::ErrorArchiveWallet => "Errore archivio wallet.",
        TextKey::ErrorRestoreWallet => "Errore ripristino wallet.",
        TextKey::ErrorCreateFlow => "Errore creazione flow.",
        TextKey::ErrorUpdateFlow => "Errore aggiornamento flow.",
        TextKey::ErrorArchiveFlow => "Errore archiviazione flow.",
        TextKey::ErrorRestoreFlow => "Errore ripristino flow.",
        TextKey::ErrorCreateCategory => "Errore creazione categoria.",
        TextKey::ErrorUpdateCategory => "Errore aggiornamento categoria.",
        TextKey::ErrorArchiveCategory => "Errore archivio categoria.",
        TextKey::ErrorCreateAlias => "Errore creazione alias.",
        TextKey::ErrorDeleteAlias => "Errore eliminazione alias.",
        TextKey::ErrorCreateVault => "Errore creazione vault.",
        TextKey::ErrorDeleteVault => "Errore eliminazione vault.",
        TextKey::ErrorSaveDefaults => "Errore salvataggio default.",
        TextKey::ErrorInvalidCredentials => "Credenziali errate o pairing mancante.",
        TextKey::ErrorMembershipLastOwner => "Non puoi rimuovere l'ultimo owner del flow.",
        TextKey::ErrorMembershipOwnerImmutable => "Non puoi cambiare il ruolo dell'owner del vault.",
        TextKey::ErrorMembershipOwnerRemoveForbidden => "Non puoi rimuovere l'owner del vault.",
        TextKey::ErrorOperationForbidden => "Operazione non permessa.",
        TextKey::ErrorResourceNotFound => "Risorsa non trovata.",
        TextKey::ErrorConflict => "Conflitto: {message}",
        TextKey::ErrorValidation => "Errore di validazione: {message}",
        TextKey::ErrorValidationAmbiguousVault => "Nome vault ambiguo. Usa \"Main (owner)\" o un vault id.",
        TextKey::ErrorBadRequest => "Richiesta non valida: {message}",
        TextKey::ErrorServerError => "Errore server: {message}",
        TextKey::ErrorServerUnreachable => "Server non raggiungibile: {error}",

        // State Messages
        TextKey::StateSnapshotUnavailable => "Snapshot non disponibile.",
        TextKey::StateVaultUnavailable => "Vault non disponibile.",
        TextKey::StateUserUnavailable => "Utente non disponibile.",
        TextKey::StateNoWalletAvailable => "Nessun wallet disponibile.",
        TextKey::StateUnallocatedMissing => "Flow Unallocated mancante.",
        TextKey::StateCannotDetermineWalletTransfer => "Impossibile determinare i wallet del transfer.",
        TextKey::StateCannotDetermineFlowTransfer => "Impossibile determinare i flow del transfer.",

        // UI Labels
        TextKey::UiOther => "Other",
        TextKey::UiError => "Error",
        TextKey::UiFailedToDeleteVault => "Failed to delete vault.",
        TextKey::UiNoDetailAvailable => "Nessun dettaglio disponibile.",
        TextKey::UiNoElement => "Nessun elemento.",
        TextKey::UiNoRecentCategories => "Nessuna categoria recente.",
        TextKey::UiRecentCategories => "Categorie recenti",

        // Prompts and Hints
        TextKey::PromptEnterName => "Inserisci un nome.",
        TextKey::PromptEnterUsername => "Inserisci un username.",
        TextKey::PromptEnterAlias => "Inserisci un alias.",
        TextKey::PromptEnterCap => "Inserisci un cap.",
        TextKey::PromptFillAllFields => "Compila tutti i campi.",
        TextKey::PromptUseDedicatedTransferForm => "Usa il form transfer dedicato.",
        TextKey::PromptAtLeastTwoCategories => "Serve almeno 2 categorie per unire.",
        TextKey::PromptSourceCategoryInvalid => "Categoria sorgente non valida.",
        TextKey::PromptDestinationCategoryInvalid => "Categoria destinazione non valida.",
        TextKey::PromptCheckConflicts => "Merge non valido. Controlla i conflitti.",
        TextKey::PromptNoShareableFlows => "Nessun flow condivisibile.",
        TextKey::PromptNoMemberSelected => "Nessun membro selezionato.",
        TextKey::PromptNoAliasSelected => "Nessun alias selezionato.",
        TextKey::PromptNoCategorySelected => "Nessuna categoria selezionata.",
        TextKey::PromptEnterCategory => "Inserisci una categoria.",

        // Quick Add / Parsing Errors
        TextKey::QuickAddEnterAmount => "Inserisci un importo.",
        TextKey::QuickAddAmountMissing => "Importo mancante.",
        TextKey::QuickAddAmountInvalid => "Importo non valido.",
        TextKey::QuickAddAmountMustBePositive => "Importo deve essere > 0.",
        TextKey::QuickAddTooManyCategories => "Troppi tag: massimo 1.",
        TextKey::QuickAddTooManyWallets => "Troppi wallet: massimo 1.",
        TextKey::QuickAddTooManyEnvelopes => "Troppi envelope: massimo 1.",
        TextKey::QuickAddSpecifyTwoWallets => "Specifica esattamente 2 wallet (@from @to).",
        TextKey::QuickAddSpecifyTwoFlows => "Specifica esattamente 2 flow (>from >to).",
        TextKey::QuickAddWalletNotFound => "Wallet non trovato: @{query}",
        TextKey::QuickAddEnvelopeNotFound => "Envelope non trovato: >{query}",
        TextKey::QuickAddFlowNotFound => "Flow non trovato: >{query}",
        TextKey::QuickAddWalletsMustBeDifferent => "I due wallet devono essere diversi.",
        TextKey::QuickAddFlowsMustBeDifferent => "I due flow devono essere diversi.",

        // Validation Errors
        TextKey::ValidationRequired => "Campo obbligatorio",
        TextKey::ValidationAmountRequired => "Importo obbligatorio",
        TextKey::ValidationAmountInvalid => "Importo non valido",
        TextKey::ValidationAmountPositive => "L'importo deve essere positivo",
        TextKey::ValidationDateRequired => "Data obbligatoria",
        TextKey::ValidationDateInvalid => "Formato data non valido (YYYY-MM-DD HH:MM)",
        TextKey::ValidationDateInvalidTimezone => "Fuso orario non valido",
        TextKey::ValidationLengthMin => "Minimo {min} caratteri",
        TextKey::ValidationLengthMax => "Massimo {max} caratteri",
        TextKey::ValidationTransferSameSource => "Scegli due wallet diversi.",
        TextKey::ValidationTransferSameDestination => "Scegli due flow diversi.",
        TextKey::ValidationTransferSameElements => "Scegli due elementi diversi.",
        TextKey::ValidationTransferMinimumTwo => "Servono almeno 2 elementi.",
        TextKey::ValidationWalletInvalid => "Wallet non valido.",
        TextKey::ValidationFlowInvalid => "Flow non valido.",
        TextKey::ValidationCategoryInvalid => "Categoria non valida.",
        TextKey::ValidationOpeningBalanceInvalid => "Saldo iniziale non valido.",
        TextKey::ValidationCapInvalid => "Cap non valido.",
        TextKey::ValidationCapMustBePositive => "Il cap deve essere > 0.",
        TextKey::ValidationOpeningBalanceNonNegative => "L'allocazione iniziale deve essere >= 0.",
        TextKey::ValidationNoWalletSelected => "Nessun wallet selezionato.",
        TextKey::ValidationNoFlowSelected => "Nessun flow selezionato.",
        TextKey::ValidationNoTransactionToVoid => "Nessuna transazione da annullare.",
        TextKey::ValidationUnallocatedCannotRename => "Unallocated non puo' essere rinominato.",
        TextKey::ValidationUnallocatedCannotArchive => "Unallocated non puo' essere archiviato.",
        TextKey::ValidationAlreadyArchived => "Gia' archiviato.",
        TextKey::ValidationSystemCategoryImmutable => "Le categorie di sistema non si modificano.",
        TextKey::ValidationNoTransactionSelected => "Nessuna transazione selezionata.",
        TextKey::ValidationNoWalletAvailable => "Nessun wallet disponibile.",
        TextKey::ValidationNoFlowAvailable => "Nessun flow disponibile.",
        TextKey::ValidationNoElementAvailable => "Nessun elemento disponibile.",
        TextKey::ValidationTransactionVoided => "Transazione annullata: modifica non disponibile.",
        TextKey::ValidationTransactionInvalid => "Transazione non valida.",
        TextKey::ValidationTransferWalletInvalid => "Transfer wallet non valido.",
        TextKey::ValidationTransferFlowInvalid => "Transfer flow non valido.",
        TextKey::ValidationWalletArchived => "Wallet archiviato: modifica non disponibile.",
        TextKey::ValidationFlowArchived => "Flow archiviato: modifica non disponibile.",
        TextKey::ValidationSnapshotUnavailable => "Snapshot non disponibile.",

        // Home screen stat cards
        TextKey::HomeCardIncome => "Entrate",
        TextKey::HomeCardExpenses => "Spese",
        TextKey::HomeCardThisMonth => "questo mese",
    }
}
