use super::TextKey;

/// Returns the Italian translation for a text key.
#[must_use]
pub fn get(key: TextKey) -> &'static str {
    match key {
        // Sections
        TextKey::SectionHome => "Home",
        TextKey::SectionTransactions => "Transazioni",
        TextKey::SectionWallets => "Portafogli",
        TextKey::SectionFlows => "Flussi",
        TextKey::SectionCategories => "Categorie",
        TextKey::SectionMembers => "Membri",
        TextKey::SectionVault => "Vault",
        TextKey::SectionStats => "Statistiche",
        TextKey::SectionPreferences => "Preferenze",

        // Form Labels
        TextKey::LabelAmount => "Importo",
        TextKey::LabelWallet => "Portafoglio",
        TextKey::LabelFlow => "Flusso",
        TextKey::LabelCategory => "Categoria",
        TextKey::LabelNote => "Nota",
        TextKey::LabelOccurredAt => "Data",
        TextKey::LabelFrom => "Da",
        TextKey::LabelTo => "A",
        TextKey::LabelName => "Nome",
        TextKey::LabelUsername => "Username",
        TextKey::LabelRole => "Ruolo",
        TextKey::LabelOpeningBalance => "Saldo iniziale",
        TextKey::LabelCap => "Limite",

        // Form Titles
        TextKey::TitleNewExpense => "Nuova Spesa",
        TextKey::TitleNewIncome => "Nuova Entrata",
        TextKey::TitleNewRefund => "Nuovo Rimborso",
        TextKey::TitleNewTransfer => "Nuovo Trasferimento",
        TextKey::TitleEditTransaction => "Modifica Transazione",
        TextKey::TitleNewWallet => "Nuovo Portafoglio",
        TextKey::TitleEditWallet => "Modifica Portafoglio",
        TextKey::TitleNewFlow => "Nuovo Flusso",
        TextKey::TitleEditFlow => "Modifica Flusso",
        TextKey::TitleNewCategory => "Nuova Categoria",
        TextKey::TitleEditCategory => "Modifica Categoria",
        TextKey::TitleNewMember => "Nuovo Membro",
        TextKey::TitleEditMember => "Modifica Membro",
        TextKey::TitleNewVault => "Nuovo Vault",
        TextKey::TitleVaultDefaults => "Impostazioni Vault",
        TextKey::TitleSelectVault => "Seleziona Vault",

        // Validation Errors
        TextKey::ValidationRequired => "Campo obbligatorio",
        TextKey::ValidationAmountRequired => "Importo obbligatorio",
        TextKey::ValidationAmountInvalid => "Importo non valido",
        TextKey::ValidationAmountPositive => "L'importo deve essere positivo",
        TextKey::ValidationAmountNegative => "L'importo deve essere negativo",
        TextKey::ValidationDateRequired => "Data obbligatoria",
        TextKey::ValidationDateInvalid => "Formato data non valido (YYYY-MM-DD HH:MM)",
        TextKey::ValidationDateInvalidTimezone => "Fuso orario non valido",
        TextKey::ValidationLengthMin => "Minimo {min} caratteri",
        TextKey::ValidationLengthMax => "Massimo {max} caratteri",
        TextKey::ValidationWalletRequired => "Seleziona un portafoglio",
        TextKey::ValidationFlowRequired => "Seleziona un flusso",
        TextKey::ValidationCategoryRequired => "Seleziona una categoria",
        TextKey::ValidationNameRequired => "Nome obbligatorio",
        TextKey::ValidationUsernameRequired => "Username obbligatorio",
        TextKey::ValidationRoleRequired => "Ruolo obbligatorio",
        TextKey::ValidationFromRequired => "Origine obbligatoria",
        TextKey::ValidationToRequired => "Destinazione obbligatoria",

        // Empty States
        TextKey::EmptyTransactions => "Nessuna transazione",
        TextKey::EmptyWallets => "Nessun portafoglio",
        TextKey::EmptyFlows => "Nessun flusso",
        TextKey::EmptyCategories => "Nessuna categoria",
        TextKey::EmptyMembers => "Nessun membro",
        TextKey::EmptyVaults => "Nessun vault",
        TextKey::EmptyStats => "Nessuna statistica disponibile",
        TextKey::EmptyResults => "Nessun risultato",

        // Actions
        TextKey::ActionSave => "Salva",
        TextKey::ActionCancel => "Annulla",
        TextKey::ActionCreate => "Crea",
        TextKey::ActionEdit => "Modifica",
        TextKey::ActionDelete => "Elimina",
        TextKey::ActionArchive => "Archivia",
        TextKey::ActionVoid => "Annulla",
        TextKey::ActionRefund => "Rimborsa",
        TextKey::ActionTransfer => "Trasferisci",
        TextKey::ActionConfirm => "Conferma",
        TextKey::ActionBack => "Indietro",
        TextKey::ActionRefresh => "Aggiorna",

        // Hints - General
        TextKey::HintPressEnter => "Premi Invio per confermare",
        TextKey::HintPressEsc => "Premi Esc per annullare",
        TextKey::HintPressTab => "Premi Tab per passare al campo successivo",
        TextKey::HintSelectWithArrows => "Usa le frecce per selezionare",
        TextKey::HintTypeToSearch => "Digita per cercare",
        TextKey::HintLoadingData => "Caricamento in corso...",
        TextKey::HintNoSelection => "Nessuna selezione",
        TextKey::HintConfirmDelete => "Premi di nuovo per confermare",

        // Hints - Footer Navigation
        TextKey::HintHome => "home",
        TextKey::HintTransactions => "txn",
        TextKey::HintAccounts => "conti",
        TextKey::HintAnalytics => "statistiche",
        TextKey::HintSettings => "impostazioni",

        // Hints - Footer Actions
        TextKey::HintQuickAdd => "aggiungi",
        TextKey::HintHelp => "aiuto",
        TextKey::HintCreate => "crea",
        TextKey::HintEdit => "modifica",
        TextKey::HintDelete => "elimina",
        TextKey::HintSave => "salva",
        TextKey::HintCancel => "annulla",
        TextKey::HintBack => "indietro",
        TextKey::HintRefresh => "aggiorna",
        TextKey::HintAdd => "aggiungi",
        TextKey::HintToggle => "seleziona",
        TextKey::HintCategorize => "categorizza",
        TextKey::HintExit => "esci",

        // Help Overlay
        TextKey::HelpTitle => "Scorciatoie da Tastiera",
        TextKey::HelpCloseHelp => "chiudi aiuto",
        TextKey::HelpGlobal => "Globale",
        TextKey::HelpNavigation => "Navigazione",
        TextKey::HelpCommonActions => "Azioni Comuni",
        TextKey::HelpQuickAddTxn => "Aggiungi transazione veloce",
        TextKey::HelpNewTxnModal => "Nuova transazione (modale)",
        TextKey::HelpCommandPalette => "Palette comandi",
        TextKey::HelpSearch => "Cerca",
        TextKey::HelpShowHelp => "Mostra/nascondi aiuto",
        TextKey::HelpNextSubTab => "Tab successivo",
        TextKey::HelpPrevSubTab => "Tab precedente",
        TextKey::HelpNavigateList => "Naviga lista",
        TextKey::HelpOpenDetails => "Apri dettagli",
        TextKey::HelpBackClose => "Indietro / Chiudi",
        TextKey::HelpEditSelected => "Modifica selezionato",
        TextKey::HelpDeleteSelected => "Elimina selezionato",
        TextKey::HelpNavigateFeed => "Naviga feed",
        TextKey::HelpGoToTransactions => "Vai a Transazioni",
        TextKey::HelpGoToAccounts => "Vai a Conti",
        TextKey::HelpGoToAnalytics => "Vai a Statistiche",
        TextKey::HelpGoToSettings => "Vai a Impostazioni",
        TextKey::HelpNewIncome => "Nuova entrata",
        TextKey::HelpNewRefund => "Nuovo rimborso",
        TextKey::HelpToggleFilters => "Mostra/nascondi filtri",
        TextKey::HelpGroupTxns => "Raggruppa transazioni",
        TextKey::HelpScopeWallet => "Filtra per portafoglio",
        TextKey::HelpScopeFlow => "Filtra per flusso",
        TextKey::HelpClearFilters => "Rimuovi filtri",
        TextKey::HelpDeleteTxn => "Elimina transazione",
        TextKey::HelpUndoDelete => "Annulla eliminazione (se visibile)",
        TextKey::HelpToggleVoided => "Mostra/nascondi annullate",
        TextKey::HelpNextPrevPage => "Pagina succ./prec.",
        TextKey::HelpVisualMode => "Modalita' Visuale",
        TextKey::HelpToggleVisual => "Attiva modalita' visuale",
        TextKey::HelpSelectTxn => "Seleziona transazione",
        TextKey::HelpExitVisual => "Esci modalita' visuale",
        TextKey::HelpDetailView => "Vista Dettaglio",
        TextKey::HelpEditTxn => "Modifica transazione",
        TextKey::HelpRepeatTxn => "Ripeti transazione",
        TextKey::HelpVoidTxn => "Annulla transazione",
        TextKey::HelpForm => "Modulo",
        TextKey::HelpNextField => "Campo successivo",
        TextKey::HelpChangeValue => "Cambia valore",
        TextKey::HelpFilters => "Filtri",
        TextKey::HelpToggleType => "Cambia tipo",
        TextKey::HelpToggleScope => "Cambia ambito",
        TextKey::HelpApply => "Applica",
        TextKey::HelpJumpSubTab => "Vai a sub-tab",
        TextKey::HelpSourcesWallets => "Fonti (Portafogli)",
        TextKey::HelpCreateWallet => "Crea portafoglio",
        TextKey::HelpRenameWallet => "Rinomina portafoglio",
        TextKey::HelpDeleteArchive => "Elimina (archivia)",
        TextKey::HelpViewDetails => "Visualizza dettagli",
        TextKey::HelpEnvelopesFlows => "Buste (Flussi)",
        TextKey::HelpCreateEnvelope => "Crea busta",
        TextKey::HelpRenameEnvelope => "Rinomina busta",
        TextKey::HelpChangeMode => "Cambia modalita'",
        TextKey::HelpGoals => "Obiettivi",
        TextKey::HelpComingSoon => "(in arrivo)",
        TextKey::HelpRefreshData => "Aggiorna dati",
        TextKey::HelpSwitchView => "Cambia vista",
        TextKey::HelpCashSpendWorth => "Cassa/Spese/Patrimonio",
        TextKey::HelpChangePeriod => "Cambia periodo",
        TextKey::HelpCreateCategory => "Crea categoria",
        TextKey::HelpRenameCategory => "Rinomina categoria",
        TextKey::HelpManageAliases => "Gestisci alias",
        TextKey::HelpMergeCategories => "Unisci categorie",
        TextKey::HelpAliases => "Alias",
        TextKey::HelpSwitchFocus => "Cambia focus",
        TextKey::HelpDeleteAlias => "Elimina alias",
        TextKey::HelpAddSave => "Aggiungi/Salva",
        TextKey::HelpVault => "Vault",
        TextKey::HelpCreateVault => "Crea vault",
        TextKey::HelpSelectVault => "Seleziona vault",
        TextKey::HelpMembers => "Membri",
        TextKey::HelpAddMember => "Aggiungi membro",
        TextKey::HelpEditMember => "Modifica membro",
        TextKey::HelpRemoveMember => "Rimuovi membro",
        TextKey::HelpVaultMembers => "Membri vault",
        TextKey::HelpFlowSharing => "Condivisione flusso",
        TextKey::HelpChangeFlow => "Cambia flusso",
        TextKey::HelpChangeRole => "Cambia ruolo",

        // Status bar
        TextKey::StatusOnline => "online",
        TextKey::StatusOffline => "offline",

        // Success Messages
        TextKey::SuccessCreated => "Creato con successo",
        TextKey::SuccessUpdated => "Aggiornato con successo",
        TextKey::SuccessDeleted => "Eliminato con successo",
        TextKey::SuccessArchived => "Archiviato con successo",
        TextKey::SuccessVoided => "Annullato con successo",
        TextKey::SuccessRefreshed => "Dati aggiornati",

        // Error Messages
        TextKey::ErrorGeneric => "Si e' verificato un errore",
        TextKey::ErrorNetwork => "Errore di connessione",
        TextKey::ErrorNotFound => "Non trovato",
        TextKey::ErrorUnauthorized => "Non autorizzato",

        // Misc
        TextKey::MiscYes => "Si",
        TextKey::MiscNo => "No",
        TextKey::MiscAll => "Tutti",
        TextKey::MiscNone => "Nessuno",
    }
}
