[package]
name = "server"
version = "0.0.1"
edition = "2021"

[lib]
name = "server"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true, features = ["typed-header"] }
engine = { path = "../engine" }
serde = { workspace = true }
sea-orm = { workspace = true, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
uuid = { workspace = true , features = ["v4", "macro-diagnostics"] }
