[package]
name = "server"
version = "0.0.1"
edition = "2021"

[lib]
name = "server"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true}
engine = { path = "../engine" }
serde = { workspace = true }
tokio = { workspace = true, features = ["full"] }
