[package]
name = "server"
version = "0.0.1"
edition = "2021"

[lib]
name = "server"
path = "src/lib.rs"

[dependencies]
axum = "0.6.18"
engine = { path = "../engine" }
serde = "1.0.160"
tokio = { version = "1.28.0", features = ["full"] }
