pub(crate) mod categories;
pub(crate) mod detail;
pub(crate) mod filter;
pub(crate) mod home;
pub(crate) mod list;
pub(crate) mod shared;
pub(crate) mod stats;
pub(crate) mod template;
pub(crate) mod wizard;
