[package]
name = "telegram_bot"
version = "0.0.1"
edition = "2021"

[lib]
name = "telegram_bot"
path = "src/lib.rs"

[dependencies]
engine = { path = "../engine" }
teloxide = { version = "0.12", features = ["macros"] }
tokio = { version = "1.26.0", features = ["macros"] }
